Repository qodo-ai/pr-agent, pull requests merged in 2023-08, with the labels that each got.

#168 Use commit messages in PR tools
  CHANGELOG.md
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_information_from_user_prompts.toml
  pr_agent/settings/pr_questions_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/settings/pr_update_changelog_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_information_from_user.py
  pr_agent/tools/pr_questions.py
  pr_agent/tools/pr_reviewer.py
  pr_agent/tools/pr_update_changelog.py
Labels: enhancement

#170 Handling edge case for hunks in git patch processing
  pr_agent/algo/git_patch_processing.py
Labels: Bug fix

#173 Optimization of PR Diff Processing
  CHANGELOG.md
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_code_suggestions.py
Labels: Refactoring

#175 Making the 'Review' Feature Great Again
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_find_line_number_of_relevant_line_in_file.py
Labels: Refactoring

#172 adding support for Anthropic, Cohere, Replicate, Azure
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handler.py
  pr_agent/algo/pr_processing.py
  pr_agent/algo/token_handler.py
  pr_agent/settings/.secrets_template.toml
  pr_agent/tools/pr_reviewer.py
  pyproject.toml
  requirements.txt
Labels: enhancement

#177 Update README and CONFIGURATION Documentation
  CONFIGURATION.md
  README.md
Labels: documentation

#181 Configurable AI Timeout
  pr_agent/algo/ai_handler.py
  pr_agent/settings/configuration.toml
Labels: enhancement

#188 Update PR Review and Description Generation to Use YAML
  pr_agent/algo/utils.py
  pr_agent/git_providers/github_provider.py
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_load_yaml.py
Labels: enhancement, Tests

#187 Limiting Description and Commit Messages Length
  pr_agent/algo/pr_processing.py
  pr_agent/algo/token_handler.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_reviewer.py
Labels: enhancement

#192 Correcting CLI and README Descriptions and Fixing Requirements.txt
  README.md
  pr_agent/cli.py
Labels: Bug fix

#194 Implementing GitHub Actions Workflow for Build and Test
  .github/workflows/build-and-test.yaml
  docker/Dockerfile
Labels: enhancement

#200 Block scalar format
  pr_agent/algo/utils.py
  pr_agent/servers/help.py
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_reviewer.py
Labels: Refactoring

#215 Addition of Automatic Review Configuration for GitHub App
  pr_agent/agent/pr_agent.py
  pr_agent/servers/github_app.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_reviewer.py
Labels: enhancement

#216 Adding Instructions for Specific Docker Image Version and GitHub Action Commit in Installation Guide
  INSTALL.md
Labels: documentation

#219 Fixing GitLab Inline Comment Diff Issue by Implementing Relevant Diff Selection
  pr_agent/git_providers/gitlab_provider.py
Labels: Bug fix

#229 Implementing Extended Improve Mode for More Thorough PR Reviews
  pr_agent/algo/ai_handler.py
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/cli.py
  pr_agent/config_loader.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/git_providers/local_git_provider.py
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/settings/pr_sort_code_suggestions_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement

#223 Enhancement: Retain Original User Description and Title in PRs
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/git_providers/local_git_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_description.py
Labels: enhancement

#228 adding huggingface inference support + litellm debugger
  INSTALL.md
  pics/debugger.png
  pr_agent/algo/ai_handler.py
  pr_agent/settings/configuration.toml
  requirements.txt
Labels: enhancement

#234 Refactoring PR Reviewer's Settings and Markdown Conversion
  pr_agent/algo/ai_handler.py
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pyproject.toml
  tests/unittest/test_convert_to_markdown.py
Labels: Refactoring

#246 Implementing Bitbucket Server Support
  docker/Dockerfile
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/secret_providers/__init__.py
  pr_agent/secret_providers/google_cloud_storage_secret_provider.py
  pr_agent/secret_providers/secret_provider.py
  pr_agent/servers/atlassian-connect.json
  pr_agent/servers/bitbucket_app.py
  pr_agent/servers/github_app.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_description.py
  pyproject.toml
  requirements.txt
Labels: enhancement

#248 Consolidation of Redundant Dependency Lists
  docker/Dockerfile
  pyproject.toml
Labels: Refactoring

#249 Enhancements to Installation Instructions and Readme
  INSTALL.md
  README.md
Labels: documentation

#250 Refactor Code to Use YAML Instead of JSON for PR Code Suggestions
  pr_agent/algo/utils.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Refactoring

#253 Enhancements to README.md
  README.md
Labels: documentation

#258 Update GitHub App Configuration Instructions
  CONFIGURATION.md
Labels: documentation

#261 Update Configuration Documentation
  CONFIGURATION.md
Labels: documentation
