Repository qodo-ai/pr-agent, pull requests merged in 2023-09, with the labels that each got.

#267 Update Documentation and README
  CONFIGURATION.md
  README.md
Labels: documentation

#264 Implementing Gitlab Webhook Secret Verification
  INSTALL.md
  README.md
  docker/Dockerfile
  pr_agent/servers/github_app.py
  pr_agent/servers/gitlab_webhook.py
Labels: enhancement

#282 Adding Similar Issue Tool and Pinecone Integration
  .github/workflows/pr-agent-review.yaml
  Usage.md
  pr_agent/agent/pr_agent.py
  pr_agent/algo/__init__.py
  pr_agent/algo/token_handler.py
  pr_agent/algo/utils.py
  pr_agent/cli.py
  pr_agent/git_providers/github_provider.py
  pr_agent/settings/.secrets_template.toml
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_similar_issue.py
  requirements.txt
Labels: enhancement

#293 Integration of Litellm Client with AI Handler
  pr_agent/algo/ai_handler.py
  pr_agent/settings/.secrets_template.toml
  pr_agent/settings/configuration.toml
  requirements.txt
Labels: enhancement

#297 Enhancing Logging in pr_similar_issue.py
  pr_agent/tools/pr_similar_issue.py
Labels: enhancement

#299 Enhancement of Similar Issue Tool and Documentation Updates
  README.md
  Usage.md
  pics/debugger.png
  pics/similar_issue_tool.png
  pr_agent/tools/pr_similar_issue.py
Labels: documentation, enhancement

#285 Markers
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_description.py
Labels: enhancement

#301 Addition of Relevant Links to README.md
  README.md
Labels: documentation

#306 Adding Estimated Review Effort Feature and Handling Cases with No Detected Language
  pr_agent/algo/language_handler.py
  pr_agent/algo/utils.py
  pr_agent/git_providers/git_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_language_handler.py
Labels: enhancement

#312 Enhancing error handling in PR review tools
  README.md
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: Refactoring

#315 Fixing potential null values in git patch processing
  pr_agent/algo/git_patch_processing.py
Labels: Bug fix

#320 Adding get_pr_id method to Git Providers
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_description.py
Labels: enhancement

#327 Update Review Guidelines to Exclude Comments
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: enhancement

#339 Enhancements to PR-Agent Documentation and Settings
  README.md
  Usage.md
  docs/ASK.md
  docs/DESCRIBE.md
  docs/IMPROVE.md
  docs/REVIEW.md
  docs/SIMILAR_ISSUE.md
  docs/TOOLS_GUIDE.md
  docs/UPDATE_CHANGELOG.md
  pics/ask.png
  pics/ask_comment.png
  pics/describe.png
  pics/describe_comment.png
  pics/improve.png
  pics/improve_comment.png
  pics/reflection_answers.png
  pics/reflection_insights.png
  pics/reflection_questions.png
  pics/review.png
  pics/review_comment.png
  pics/similar_issue.png
  pics/similar_issue_comment.png
  pics/similar_issue_original_issue.png
  pics/similar_issue_tool.png
  pics/update_changelog.png
  pics/update_changelog_comment.png
  pr_agent/agent/pr_agent.py
Labels: documentation, enhancement

#340 Update Documentation and CLI Execution Method
  INSTALL.md
  docs/IMPROVE.md
  docs/REVIEW.md
Labels: documentation, Refactoring

#341 Update and Refactor Documentation
  Usage.md
Labels: documentation
