Repository qodo-ai/pr-agent, pull requests merged in 2023-11, with the labels that each got.

#416 Fix formatting when last commit message contains _
  pr_agent/tools/pr_reviewer.py
Labels: Bug fix

#424 Update Bitbucket Provider to Use 'position' Instead of 'start_line' for Inline Comments
  pr_agent/git_providers/bitbucket_provider.py
Labels: Bug fix

#415 Refactor Command Handling for Different Triggers
  pr_agent/servers/github_app.py
Labels: Refactoring

#427 Adding Middleware to FastAPI Initialization
  pr_agent/servers/serverless.py
Labels: Bug fix

#428 Enhancements and Fixes in Bitbucket Provider
  INSTALL.md
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: documentation, enhancement, Bug fix

#430 Fix PR Description Prompt and Data Preparation
  pr_agent/settings/pr_description_prompts.toml
Labels: Bug fix

#423 Implementing Thresholds for Incremental PR Reviews
  docs/REVIEW.md
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_reviewer.py
Labels: enhancement

#431 Refactoring PR Labels Handling and Display
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_custom_labels.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: Refactoring

#439 Enhancement of Patch Handling and PR Processing
  pr_agent/algo/file_filter.py
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: enhancement

#441 Add Persistent Review Feature to PR Agent
  RELEASE_NOTES.md
  Usage.md
  docs/REVIEW.md
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_reviewer.py
Labels: enhancement

#444 Implementing Fallback Mechanisms for YAML Parsing
  pr_agent/algo/utils.py
  tests/unittest/try_fix_yaml.py
Labels: enhancement

#449 Fix `get_user_description` in case `pr_description.enable_pr_type=false`
  pr_agent/git_providers/git_provider.py
Labels: Bug fix

#451 Enhancement of Persistent Comments in PR Review
  docs/REVIEW.md
  pr_agent/algo/pr_processing.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement

#452 Add Review Labels for Security and Effort Estimation
  .pr_agent.toml
  docs/REVIEW.md
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Review effort [1-5]: 3

#436 Support Google's Vertex AI
  Usage.md
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handler.py
  pr_agent/settings/.secrets_template.toml
  requirements.txt
Labels: enhancement, Review effort [1-5]: 3

#453 Version 0.10 Release and Workflow Update
  .github/workflows/pr-agent-review.yaml
  RELEASE_NOTES.md
Labels: enhancement

#438 Removal of Redundant Logger Setup
  pr_agent/servers/serverless.py
Labels: Refactoring, Review effort [1-5]: 1

#460 GFM mode for 'review' instructions
  INSTALL.md
  pr_agent/servers/help.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Review effort [1-5]: 2

#462 Enhancements in YAML Parsing and Error Handling
  pr_agent/algo/utils.py
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_load_yaml.py
Labels: Refactoring, Review effort [1-5]: 2

#464 Refactor YAML parsing for improved error handling
  pr_agent/algo/utils.py
  tests/unittest/test_load_yaml.py
Labels: Refactoring, Review effort [1-5]: 2

#466 Fix a bug in GitLab webhook
  pr_agent/servers/gitlab_webhook.py
Labels: Review effort [1-5]: 1

#467 Add support for base_url in GitHub SDK
  pr_agent/git_providers/github_provider.py
  pr_agent/settings/configuration.toml
Labels: Review effort [1-5]: 2

#469 Improve Documentation in Usage.md
  Usage.md
Labels: documentation, Review effort [1-5]: 1

#470 Enhance glob pattern handling and logging in file filtering
  Usage.md
  pr_agent/algo/file_filter.py
  pr_agent/algo/utils.py
Labels: enhancement, Review effort [1-5]: 2

#455 Added BitBucket Server and Data Center support
  INSTALL.md
  docker/Dockerfile
  pr_agent/git_providers/__init__.py
  pr_agent/git_providers/bitbucket_server_provider.py
  pr_agent/servers/bitbucket_server_webhook.py
  tests/unittest/test_bitbucket_provider.py
Labels: Review effort [1-5]: 4

#447 Refactor PR label handling and update CLI commands
  pr_agent/algo/language_handler.py
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/cli.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/codecommit_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/settings/custom_labels.toml
  pr_agent/settings/pr_add_docs.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_custom_labels.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_information_from_user_prompts.toml
  pr_agent/settings/pr_questions_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/settings/pr_sort_code_suggestions_prompts.toml
  pr_agent/settings/pr_update_changelog_prompts.toml
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_generate_labels.py
  tests/unittest/test_clip_tokens.py
Labels: enhancement, Refactoring, Review effort [1-5]: 4

#476 Enhancements and Bug Fixes in Code Suggestions and Line Link Generation
  docs/IMPROVE.md
  pics/improved_summerize_closed.png
  pics/improved_summerize_open.png
  pr_agent/algo/utils.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_convert_to_markdown.py
  tests/unittest/test_parse_code_suggestion.py
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#481 Refactoring Environment Variables Access
  .github/workflows/pr-agent-review.yaml
  pr_agent/servers/github_action_runner.py
Labels: Refactoring

#485 Enhancement of Inline Comment Publishing in Bitbucket Provider and Logging Addition
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Review effort [1-5]: 2

#489 Improve error handling in settings retrieval
  pr_agent/servers/github_action_runner.py
Labels: Review effort [1-5]: 1

#490 Alphabetical Reordering of requirements.txt
  requirements.txt
Labels: Refactoring

#492 Update IMPROVE.md
  docs/IMPROVE.md
Labels: Review effort [1-5]: 1
