Repository qodo-ai/pr-agent, pull requests merged in 2023-10, with the labels that each got.

#343 Update Documentation and Prompts
  README.md
  Usage.md
  docs/TOOLS_GUIDE.md
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: documentation, enhancement

#337 Add code documentations in PR
  README.md
  docs/ADD_DOCUMENTATION.md
  docs/TOOLS_GUIDE.md
  pics/add_docs.png
  pics/add_docs_comment.png
  pr_agent/agent/pr_agent.py
  pr_agent/config_loader.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_add_docs.toml
  pr_agent/tools/pr_add_docs.py
Labels: enhancement

#349 Update Documentation for PR Compression and Large PR Handling
  PR_COMPRESSION.md
  Usage.md
Labels: documentation

#352 Refactoring Patch Extra Lines and Updating Prompts
  Usage.md
  pr_agent/algo/pr_processing.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_add_docs.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/settings/pr_update_changelog_prompts.toml
  pr_agent/tools/pr_add_docs.py
Labels: Refactoring

#354 Enhancements in Markdown Conversion and Line Number Linking
  Usage.md
  pr_agent/algo/utils.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement

#382 Enhancements and Error Handling in Similar Issue Tool
  pr_agent/tools/pr_similar_issue.py
Labels: Refactoring, Bug fix

#386 Refactor Bitbucket Pipeline Integration and Update Documentation
  Dockerfile.bitbucket_pipeline
  INSTALL.md
  bitbucket_pipeline/entrypoint.sh
  pr_agent/servers/bitbucket_pipeline_runner.py
Labels: documentation, Refactoring

#390 Enhancing Documentation and Updating Configuration for PR Descriptions
  docs/IMPROVE.md
  docs/REVIEW.md
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_description.py
Labels: documentation, enhancement, Refactoring

#385 Add Blacklist for Non-Editable File Extensions in Documentation
  pr_agent/settings/language_extensions.toml
  pr_agent/tools/pr_add_docs.py
Labels: enhancement

#387 Enhancing Logging in Bitbucket, GitLab, and Google Cloud Storage Secret Provider
  pr_agent/secret_providers/google_cloud_storage_secret_provider.py
  pr_agent/servers/bitbucket_app.py
  pr_agent/servers/gitlab_webhook.py
Labels: enhancement

#391 Update and Enhance DESCRIBE.md Documentation
  docs/DESCRIBE.md
  pics/describe_markers_after.png
  pics/describe_markers_before.png
  pr_agent/tools/pr_description.py
Labels: documentation

#398 Update Documentation and Installation Instructions
  INSTALL.md
  README.md
  Usage.md
Labels: documentation

#402 Update GitHub Action to Use .pr_agent.toml
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/utils.py
  pr_agent/servers/github_action_runner.py
Labels: Refactoring

#403 Refactoring Custom Labels Handling and Documentation Update
  docs/GENERATE_CUSTOM_LABELS.md
  pr_agent/settings/custom_labels.toml
  pr_agent/tools/pr_generate_labels.py
  pr_agent/tools/pr_reviewer.py
Labels: documentation, Refactoring

#405 Final Fixes and Updates to PR Agent
  RELEASE_NOTES.md
  Usage.md
  docs/GENERATE_CUSTOM_LABELS.md
  pr_agent/algo/utils.py
  pr_agent/servers/github_action_runner.py
Labels: documentation, Refactoring

#407 Enhance GitHub App features documentation in Usage.md
  Usage.md
Labels: documentation

#411 Add Logging Context to Handle Request Calls in gitlab_webhook.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/servers/gitlab_webhook.py
Labels: Refactoring

#413 Update Method to Fetch Repository Settings in bitbucket_provider.py
  pr_agent/git_providers/bitbucket_provider.py
Labels: Refactoring

#414 Bugfix: ignored github_app.commands on .pr-agent.toml
  pr_agent/servers/github_app.py
Labels: Refactoring
