Repository qodo-ai/pr-agent, pull requests merged in 2023-07, with the labels that each got.

#7 Fix encoding error on special_tokens
  pr_agent/algo/token_handler.py
Labels: bug

#3 Combine all modified and deleted files that been compressed to the prompt
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  tests/unit/test_handle_patch_deletions.py
  tests/unit/test_language_handler.py
Labels: enhancement

#76 Optimization of Inline Comments Publishing
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_reviewer.py
  requirements.txt
Labels: question

#83 Support describe for Gitlab
  README.md
  pr_agent/algo/pr_processing.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_reviewer.py
Labels: Gitlab

#100 Enhancement of Code Review Functionality
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/servers/help.py
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
Labels: Refactoring

#102 Refactoring Question Handling in CLI
  pr_agent/cli.py
Labels: Refactoring

#101 Adding Docstrings to Python Files
  pr_agent/algo/ai_handler.py
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  pr_agent/algo/token_handler.py
  pr_agent/algo/utils.py
Labels: documentation

#103 Update README.md
  README.md
Labels: documentation

#90 Add Option to Control Comment Publishing Progress
  pr_agent/git_providers/github_provider.py
  pr_agent/settings/configuration.toml
Labels: enhancement

#108 Configurable Language Extensions
  pr_agent/algo/language_handler.py
  pr_agent/config_loader.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/language_extensions.toml
Labels: enhancement

#113 Refactoring CLI Commands Handling
  pr_agent/cli.py
Labels: Refactoring

#114 Update README GIFs
  README.md
Labels: documentation

#115 Update Installation Instructions in README
  INSTALL.md
Labels: documentation

#117 Implementing Fallback Models for Tokenization
  pr_agent/algo/pr_processing.py
  pr_agent/algo/token_handler.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_information_from_user.py
  pr_agent/tools/pr_questions.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement

#118 Handling exceptions in fallback models
  pr_agent/algo/pr_processing.py
Labels: Bug fix

#119 Optimize Code Suggestions API Calls
  pr_agent/git_providers/github_provider.py
Labels: Refactoring

#121 Update GIF URLs in README
  README.md
Labels: documentation

#126 Add functionality to preserve existing labels in PRs
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_description.py
Labels: enhancement

#125 Code Enhancement in PR Agent
  pr_agent/servers/github_action_runner.py
  pr_agent/tools/pr_description.py
Labels: Refactoring

#134 Use OAuth token for GitLab API
  pr_agent/git_providers/gitlab_provider.py
Labels: Refactoring

#128 Add Local Git Provider Support
  pr_agent/algo/language_handler.py
  pr_agent/config_loader.py
  pr_agent/git_providers/__init__.py
  pr_agent/git_providers/local_git_provider.py
  pr_agent/settings/configuration.toml
  requirements.txt
Labels: enhancement

#132 Enhancement of GitHub Webhook and Polling Server
  pr_agent/servers/github_app.py
  pr_agent/servers/github_polling.py
Labels: Refactoring

#140 Enhancement of PRReviewer class in pr_reviewer.py
  pr_agent/tools/pr_reviewer.py
Labels: Refactoring

#142 Improvements to Local Git Provider
  pr_agent/git_providers/local_git_provider.py
Labels: Refactoring

#139 Add feature to update CHANGELOG.md based on PR content
  CHANGELOG.md
  README.md
  pr_agent/agent/pr_agent.py
  pr_agent/cli.py
  pr_agent/config_loader.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_update_changelog.toml
  pr_agent/tools/pr_update_changelog.py
Labels: enhancement

#144 Update README with 'Why use PR-Agent?' section
  README.md
Labels: documentation

#133 Handling GitHub API Rate Limit Exceeded Exception
  pr_agent/algo/pr_processing.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/servers/utils.py
  pr_agent/settings/configuration.toml
Labels: enhancement, Bug fix

#146 Fix for GitLab Paginator in GitLab Provider
  pr_agent/git_providers/gitlab_provider.py
Labels: Bug fix

#141 Transition to pip package with pyproject.toml
  .gitignore
  Dockerfile.github_action
  docker/Dockerfile
  docker/Dockerfile.lambda
  pyproject.toml
  requirements.txt
  setup.py
Labels: Refactoring

#150 Github App: handle concurrent requests from multiple installations of app
  pr_agent/git_providers/github_provider.py
  pr_agent/servers/github_app.py
  pyproject.toml
Labels: enhancement

#152 Improvements and Error Handling for GitLab Provider
  CHANGELOG.md
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_code_suggestions.py
Labels: Bug fix

#159 The Configurator Strikes Back
  CHANGELOG.md
  pr_agent/agent/pr_agent.py
  pr_agent/algo/utils.py
  pr_agent/cli.py
  pr_agent/config_loader.py
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/settings/pr_update_changelog_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_information_from_user.py
  pr_agent/tools/pr_reviewer.py
  pr_agent/tools/pr_update_changelog.py
Labels: enhancement
