Repository qodo-ai/pr-agent, pull requests merged in 2023-12, with the labels that each got.

#497 Update pr-agent/docs/Review.md Image
  docs/REVIEW.md
Labels: bug_fix

#498 Update Image URLs in Markdown Documentation
  PR_COMPRESSION.md
  README.md
  docs/ADD_DOCUMENTATION.md
  docs/ASK.md
  docs/DESCRIBE.md
  docs/GENERATE_CUSTOM_LABELS.md
  docs/IMPROVE.md
  docs/REVIEW.md
  docs/SIMILAR_ISSUE.md
  docs/UPDATE_CHANGELOG.md
  pics/add_docs.png
  pics/add_docs_comment.png
  pics/ask.png
  pics/ask_comment.png
  pics/custom_label_published.png
  pics/custom_labels_list.png
  pics/describe.png
  pics/describe_comment.png
  pics/describe_markers_after.png
  pics/describe_markers_before.png
  pics/improve.png
  pics/improve_comment.png
  pics/improved_summerize_closed.png
  pics/improved_summerize_open.png
  pics/incremental_review.png
  pics/logo-dark.png
  pics/logo-light.png
  pics/reflection_answers.png
  pics/reflection_insights.png
  pics/reflection_questions.png
  pics/review.png
  pics/review_comment.png
  pics/similar_issue.png
  pics/similar_issue_comment.png
  pics/similar_issue_original_issue.png
  pics/update_changelog.png
  pics/update_changelog_comment.png
Labels: documentation, Review effort [1-5]: 1

#500 Enhance pr_url assignment in github_provider.py for GitHub Actions compatibility
  pr_agent/git_providers/github_provider.py
Labels: enhancement, Review effort [1-5]: 1

#505 Update Usage.md with BitBucket Self-Hosted App section
  Usage.md
Labels: documentation, Review effort [1-5]: 1

#450 Specify Cache Directory in Azure DevOps in Lambda Function Setup
  INSTALL.md
Labels: clarification needed

#508 docs: Update issue link in INSTALL.md and enhance key formatting in p…
  INSTALL.md
  pr_agent/tools/pr_description.py
Labels: Review effort [1-5]: 1

#509 Enhancement of PR Description and Labeling Features
  pr_agent/algo/utils.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/custom_labels.toml
  pr_agent/settings/pr_custom_labels.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_description.py
Labels: enhancement, Review effort [1-5]: 4

#512 Refactoring and Enhancement of PR Description Formatting in 'pr_description.py'
  RELEASE_NOTES.md
  docs/DESCRIBE.md
  pr_agent/tools/pr_description.py
Labels: enhancement, Review effort [1-5]: 3

#515 Enhancement of Code Feedback Formatting in utils.py
  pr_agent/algo/utils.py
  pr_agent/git_providers/gitlab_provider.py
  tests/unittest/test_convert_to_markdown.py
Labels: enhancement, Review effort [1-5]: 3

#516 Refine README.md for clarity and precision
  README.md
Labels: documentation, Review effort [1-5]: 1

#517 Improve PR description formatting and handling in pr_description.py
  pr_agent/tools/pr_description.py
Labels: Review effort [1-5]: 2

#511 Enhancement: Apply Repository Settings on Every 'Synchronize' Event
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 2

#519 Enhancement: Automatic Tool Configuration for Bitbucket App
  Usage.md
  pr_agent/servers/bitbucket_app.py
  pr_agent/settings/configuration.toml
Labels: Review effort [1-5]: 3

#520 Refactor auto tool execution order and enhance logging and documentation
  Usage.md
  pr_agent/servers/bitbucket_app.py
  pr_agent/tools/pr_description.py
Labels: enhancement, Review effort [1-5]: 2

#521 feat: Enable PR description publishing as comment in bitbucket_app.py
  Usage.md
  pr_agent/servers/bitbucket_app.py
Labels: Review effort [1-5]: 1

#524 feat: Add repository labels retrieval function in gitlab_provider.py
  pr_agent/git_providers/gitlab_provider.py
Labels: Review effort [1-5]: 1

#525 Refactoring AI Handlers and Adding Support for Multiple AI Models
  pr_agent/agent/pr_agent.py
  pr_agent/algo/ai_handlers/base_ai_handler.py
  pr_agent/algo/ai_handlers/langchain_ai_handler.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/algo/ai_handlers/openai_ai_handler.py
  pr_agent/algo/utils.py
  pr_agent/tools/pr_add_docs.py
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_generate_labels.py
  pr_agent/tools/pr_information_from_user.py
  pr_agent/tools/pr_questions.py
  pr_agent/tools/pr_reviewer.py
  pr_agent/tools/pr_update_changelog.py
  requirements.txt
Labels: enhancement, Review effort [1-5]: 4

#530 Enhancement: Implement label case conversion and update label descriptions in settings files
  pr_agent/algo/utils.py
  pr_agent/settings/pr_custom_labels.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_generate_labels.py
Labels: enhancement, Review effort [1-5]: 3

#531 Update pr-agent-review.yaml
  .github/workflows/pr-agent-review.yaml
Labels: enhancement, Review effort [1-5]: 1

#532 Hl/native labels readme
  docs/DESCRIBE.md
  docs/GENERATE_CUSTOM_LABELS.md
Labels: documentation, Review effort [1-5]: 1

#533 bug fix
  pr_agent/algo/utils.py
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 2

#537 Enhancement of AI Response Parsing Mechanism
  pr_agent/algo/utils.py
  tests/unittest/test_try_fix_yaml.py
Labels: Review effort [1-5]: 2

#540 Enhancement of PR Description Formatting and Instructions Update
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_description.py
Labels: Review effort [1-5]: 1

#541 feat: Enhance YAML parsing with additional fallbacks and key customiz…
  pr_agent/algo/utils.py
Labels: Review effort [1-5]: 2

#542 Enhancement: Update PR Description Configuration and Prompts
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_generate_labels.py
Labels: enhancement, Review effort [1-5]: 2

#545 feat: Improve suggestion formatting in markdown text generation
  pr_agent/algo/utils.py
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: Review effort [1-5]: 1

#546 Single-label for suggestions
  docs/IMPROVE.md
  pr_agent/algo/pr_processing.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/bitbucket_server_provider.py
  pr_agent/git_providers/codecommit_provider.py
  pr_agent/git_providers/gerrit_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/git_providers/local_git_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 4

#547 Readme for PR-Agent-Pro
  README.md
  docs/ADD_DOCUMENTATION.md
  docs/Analyze.md
  docs/Full_enviroments.md
  docs/GENERATE_CUSTOM_LABELS.md
  docs/TOOLS_GUIDE.md
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 1

#548 LanceDB Integration
  docs/SIMILAR_ISSUE.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_similar_issue.py
  requirements.txt
Labels: Review effort [1-5]: 4

#550 feat: Refactor help text addition in pr_reviewer.py and update tool n…
  README.md
  pr_agent/algo/utils.py
  pr_agent/servers/help.py
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_convert_to_markdown.py
Labels: Review effort [1-5]: 2

#551 global configuration
  Usage.md
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
Labels: Review effort [1-5]: 2

#552 Add `enable_help_text` setting and update PR review preparation method
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_reviewer.py
Labels: Review effort [1-5]: 2

#554 fix: missing flag in INSTALL.md
  INSTALL.md
Labels: Review effort [1-5]: 1

#556 Update Usage.md
  Usage.md
Labels: Review effort [1-5]: 1
