Repository qodo-ai/pr-agent, pull requests merged in 2024-07, with the labels that each got.

#1011 Tr/review redesign
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/algo/utils.py
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#1016 tests
  pr_agent/algo/utils.py
  tests/unittest/test_convert_to_markdown.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#1020 Tr/fallbacks
  pr_agent/algo/utils.py
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_try_fix_yaml.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#1021 increase margins
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
Labels: enhancement, Review effort [1-5]: 1

#1022 sonnet-3.5
  README.md
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#1025 refresh message
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Review effort [1-5]: 2

#1028 GitHub Enterprise Server
  docs/docs/installation/pr_agent_pro.md
  docs/docs/overview/pr_agent_pro.md
  pr_agent/git_providers/github_provider.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#1029 Tr/best practice
  docs/docs/tools/improve.md
  docs/mkdocs.yml
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_code_suggestions_reflect_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#1030 add additional google models support
  pr_agent/algo/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#1035 Tr/providers
  pr_agent/algo/utils.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#1037 example best practice
  docs/docs/installation/github.md
  docs/docs/overview/pr_agent_pro.md
  docs/docs/tools/improve.md
  docs/docs/usage-guide/EXAMPLE_BEST_PRACTICE.md
Labels: documentation, Review effort [1-5]: 2

#1038 example best practice
  docs/docs/overview/pr_agent_pro.md
  docs/docs/tools/improve.md
  docs/docs/tools/review.md
Labels: documentation, Review effort [1-5]: 1

#1040 review with links
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_reviewer.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#1042 Update GitHub Action documentation for Docker image stability and security
  docs/docs/installation/github.md
Labels: documentation, Review effort [1-5]: 1

#1046 PR-Agent Pro Models
  README.md
  docs/docs/css/custom.css
  docs/docs/index.md
  docs/docs/installation/bitbucket.md
  docs/docs/installation/index.md
  docs/docs/usage-guide/PR_agent_pro_models.md
  docs/docs/usage-guide/automations_and_usage.md
  docs/docs/usage-guide/configuration_options.md
  docs/docs/usage-guide/index.md
  docs/docs/usage-guide/introduction.md
  docs/mkdocs.yml
Labels: documentation, Review effort [1-5]: 1

#1048 fix broken output format(yaml) prompt
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: enhancement, Bug fix, Review effort [1-5]: 1

#1052 docs: Supports litellm's Amazon Bedrock parameter syntax change
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/settings/.secrets_template.toml
Labels: documentation, Review effort [1-5]: 1

#1059 bitbucket server
  pr_agent/git_providers/bitbucket_server_provider.py
  pr_agent/servers/bitbucket_server_webhook.py
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#1061 Implement BitbucketServerProvider.get_line_link
  pr_agent/git_providers/bitbucket_server_provider.py
Labels: enhancement, Review effort [1-5]: 2

#1063 Add end-to-end tests for GitHub, GitLab, and Bitbucket apps; added seed
  .github/workflows/build-and-test.yaml
  .github/workflows/e2e_tests.yaml
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_add_docs.py
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_generate_labels.py
  pr_agent/tools/pr_information_from_user.py
  pr_agent/tools/pr_line_questions.py
  pr_agent/tools/pr_questions.py
  pr_agent/tools/pr_reviewer.py
  pr_agent/tools/pr_update_changelog.py
  tests/e2e_tests/e2e_utils.py
  tests/e2e_tests/test_bitbucket_app.py
  tests/e2e_tests/test_github_app.py
  tests/e2e_tests/test_gitlab_webhook.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#1065 Add Llama 3.1 and Mixtral 8x7B for Groq
  pr_agent/algo/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#1066 docs: update usage guide for changing models; add custom model support and reorganize sections
  docs/docs/usage-guide/additional_configurations.md
  docs/docs/usage-guide/changing_a_model.md
  docs/docs/usage-guide/index.md
  docs/mkdocs.yml
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 3

#1067 docs: update usage guide and README; fix minor formatting issues in u…
  README.md
  docs/docs/usage-guide/changing_a_model.md
  docs/docs/usage-guide/index.md
  pr_agent/algo/utils.py
  pr_agent/tools/pr_code_suggestions.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#1069 watson_models
  pr_agent/algo/__init__.py
Labels: enhancement, Review effort [1-5]: 2

#1075 Add missing bitbucket_server.pr_commands default
  pr_agent/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 1, Configuration changes
