Repository qodo-ai/pr-agent, pull requests merged in 2024-09, with the labels that each got.

#1193 Tr/updates
  pr_agent/algo/git_patch_processing.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#1194 docs: update PR-Agent Pro documentation with new features and improve…
  README.md
  docs/docs/overview/pr_agent_pro.md
  docs/docs/tools/improve.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#1195 docs: update PR-Agent Pro documentation with new features and improve…
  docs/docs/overview/pr_agent_pro.md
  docs/docs/tools/improve.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#1172 Bugfix/bb 2 way diff fix
  pr_agent/git_providers/bitbucket_server_provider.py
  tests/unittest/test_bitbucket_provider.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#1196 Update README.md
  README.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#1197 Add 1C Enterprise language
  pr_agent/settings/language_extensions.toml
Labels: enhancement, Review effort [1-5]: 1

#1198 Tr/polling
  pr_agent/servers/github_polling.py
Labels: enhancement, Review effort [1-5]: 4

#1192 feat: gitlab skip source, target and labels
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/servers/github_app.py
  pr_agent/servers/gitlab_webhook.py
  pr_agent/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 3

#1201 Tr/ignore titile adjustments
  docs/docs/usage-guide/additional_configurations.md
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/servers/bitbucket_app.py
  pr_agent/servers/github_app.py
  pr_agent/servers/gitlab_webhook.py
  pr_agent/settings/configuration.toml
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#1202 avoid_full_files
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 2

#1205 fix: Typo in README (`Chrom` -> `Chrome`)
  README.md
Labels: documentation, Review effort [1-5]: 1

#1206 ai_metadat_injection
  docs/docs/core-abilities/code_oriented_yaml.md
  docs/docs/core-abilities/compression_strategy.md
  docs/docs/core-abilities/dynamic_context.md
  docs/docs/core-abilities/impact_evaluation.md
  docs/docs/core-abilities/index.md
  docs/docs/core-abilities/interactivity.md
  docs/docs/core-abilities/line_localization.md
  docs/docs/core-abilities/metadata.md
  docs/docs/core-abilities/self_reflection.md
  docs/docs/core-abilities/static_code_analysis.md
  docs/mkdocs.yml
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  pr_agent/algo/types.py
  pr_agent/algo/utils.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/servers/azuredevops_server_webhook.py
  pr_agent/servers/bitbucket_app.py
  pr_agent/servers/github_app.py
  pr_agent/servers/gitlab_webhook.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_add_docs.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_code_suggestions_reflect_prompts.toml
  pr_agent/settings/pr_line_questions_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
  requirements.txt
  tests/unittest/test_extend_patch.py
Labels: enhancement, Review effort [1-5]: 3

#1207 Tr/fixes metadata
  docs/docs/core-abilities/metadata.md
  pr_agent/algo/utils.py
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1208 config docs
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_config.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#1210 bug fix: remove unused get_pr_description method from Azure DevOps
  pr_agent/git_providers/azuredevops_provider.py
Labels: Bug fix, Review effort [1-5]: 1

#1211 impact docs
  docs/docs/core-abilities/impact_evaluation.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#1212 docs
  docs/docs/core-abilities/impact_evaluation.md
  docs/docs/core-abilities/index.md
  docs/docs/core-abilities/line_localization.md
  docs/docs/tools/improve.md
  docs/mkdocs.yml
Labels: documentation, Review effort [1-5]: 2

#1214 docs
  docs/docs/chrome-extension/features.md
  docs/docs/overview/pr_agent_pro.md
  docs/docs/tools/improve.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#1215 docs
  docs/docs/overview/pr_agent_pro.md
Labels: documentation, Review effort [1-5]: 1

#1217 Update index.md
  docs/docs/index.md
Labels: documentation, Review effort [1-5]: 1

#1219 docs and fixes
  docs/docs/core-abilities/static_code_analysis.md
  docs/docs/tools/analyze.md
  docs/docs/tools/test.md
  pr_agent/algo/utils.py
  pr_agent/servers/github_polling.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#1220 FAQ
  docs/docs/core-abilities/index.md
  docs/docs/faq/index.md
  docs/mkdocs.yml
Labels: documentation, enhancement, Review effort [1-5]: 2

#1221 FAQ
  docs/docs/faq/index.md
  docs/mkdocs.yml
Labels: documentation, Review effort [1-5]: 1

#1222 enhance: cap patch extra lines and update documentation with separato…
  docs/docs/faq/index.md
  docs/docs/tools/review.md
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/algo/pr_processing.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#1223 Update additional_configurations.md
  docs/docs/usage-guide/additional_configurations.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#1224 Tr/dynamic context
  README.md
  docs/docs/core-abilities/dynamic_context.md
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#1226 Add new o1-mini and o1-preview models
  pr_agent/algo/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#1227 refactor logic
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_extend_patch.py
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#1228 Set azure devops default status to ByDesign
  pr_agent/git_providers/azuredevops_provider.py
Labels: enhancement, Review effort [1-5]: 1

#1230 Tr/dynamic
  docs/docs/tools/improve.md
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#1233 collapsible
  docs/docs/tools/improve.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#1234 self_reflection
  docs/docs/core-abilities/self_reflection.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#1231 Update PR Action Handling Logic in GitHub Action Runner
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/servers/github_action_runner.py
  pr_agent/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 2

#1232 func get_line_link compatible with old gitlab versions
  pr_agent/git_providers/gitlab_provider.py
Labels: enhancement, Review effort [1-5]: 1

#1236 TLDR
  docs/docs/core-abilities/dynamic_context.md
  docs/docs/core-abilities/metadata.md
  docs/docs/core-abilities/self_reflection.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#1241 Add PR help message functionality and update dependencies
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_help_message.py
  requirements.txt
Labels: enhancement, Review effort [1-5]: 4

#1242 prompts
  pr_agent/config_loader.py
  pr_agent/settings/pr_help_prompts.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#1243 get protection
  pr_agent/tools/pr_help_message.py
Labels: enhancement

#1244 Refactor S3 file handling and update Dockerfile to include local Chroma DB file
  docker/Dockerfile
  docs/chroma_db.zip
  pr_agent/tools/pr_help_message.py
Labels: enhancement, Review effort [1-5]: 2

#1245 docs pr help
  README.md
  docs/docs/index.md
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_help_message.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#1246 update docs
  docs/docs/tools/improve.md
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#1247 Tr/help fixes
  docs/chroma_db.zip
  pr_agent/settings/pr_help_prompts.toml
  pr_agent/tools/pr_help_message.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#1248 DocHelper
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_help_message.py
Labels: enhancement, Review effort [1-5]: 2

#1250 docs: improve GitLab installation instruction
  docs/docs/installation/gitlab.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#1252 improve code suggestion prompt
  docs/docs/usage-guide/PR_agent_pro_models.md
  pr_agent/algo/git_patch_processing.py
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_code_suggestions_reflect_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement

#1253 Add configuration for auto actions in GitHub Action runner
  pr_agent/servers/github_action_runner.py
Labels: enhancement, Review effort [1-5]: 2

#1254 Add intro and chat text options for PR code suggestions in configuration
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Review effort [1-5]: 2

#1255 Enable intro and chat text for PR code suggestions in configuration
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Review effort [1-5]: 2, Configuration

#1257 docs: update PR-Agent documentation with PR Chat search instructions
  docs/docs/index.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#1259 Add intro text option for PR reviews in configuration and utils
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
  tests/unittest/test_convert_to_markdown.py
Labels: enhancement, Review effort [1-5]: 2

#1260 Update CNAME
  docs/docs/CNAME
Labels: enhancement, Review effort [1-5]: 1

#1261 Qodo Merge rename
  docs/README.md
  docs/docs/chrome-extension/data_privacy.md
  docs/docs/chrome-extension/features.md
  docs/docs/chrome-extension/index.md
  docs/docs/core-abilities/dynamic_context.md
  docs/docs/core-abilities/impact_evaluation.md
  docs/docs/core-abilities/index.md
  docs/docs/core-abilities/metadata.md
  docs/docs/core-abilities/self_reflection.md
  docs/docs/core-abilities/static_code_analysis.md
  docs/docs/faq/index.md
  docs/docs/finetuning_benchmark/index.md
  docs/docs/index.md
  docs/docs/installation/azure.md
  docs/docs/installation/bitbucket.md
  docs/docs/installation/github.md
  docs/docs/installation/gitlab.md
  docs/docs/installation/index.md
  docs/docs/installation/pr_agent_pro.md
  docs/docs/overview/data_privacy.md
  docs/docs/overview/index.md
  docs/docs/overview/pr_agent_pro.md
  docs/docs/tools/custom_labels.md
  docs/docs/tools/describe.md
  docs/docs/tools/help.md
  docs/docs/tools/improve.md
  docs/docs/tools/index.md
  docs/docs/tools/review.md
  docs/docs/tools/similar_code.md
  docs/docs/usage-guide/PR_agent_pro_models.md
  docs/docs/usage-guide/additional_configurations.md
  docs/docs/usage-guide/automations_and_usage.md
  docs/docs/usage-guide/configuration_options.md
  docs/docs/usage-guide/index.md
  docs/docs/usage-guide/introduction.md
  docs/docs/usage-guide/mail_notifications.md
  docs/mkdocs.yml
Labels: documentation, Review effort [1-5]: 4

#1256 disable chat message for github action
  pr_agent/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 1

#1262 style: refine field descriptions in KeyIssuesComponentLink model
  pr_agent/algo/utils.py
  pr_agent/settings/pr_reviewer_prompts.toml
  tests/unittest/test_convert_to_markdown.py
Labels: enhancement, Review effort [1-5]: 2
