Repository qodo-ai/pr-agent, pull requests merged in 2024-03, with the labels that each got.

#729 wiki
  README.md
  Usage.md
  pr_agent/servers/github_app.py
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#732 Remove functionality and references to 'remove_previous_review_comment'
  Usage.md
  docs/REVIEW.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Review effort [1-5]: 2

#730 Enhance markdown formatting fo issues
  pr_agent/algo/utils.py
  pr_agent/settings/pr_reviewer_prompts.toml
  tests/unittest/test_convert_to_markdown.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#733 readme updates
  README.md
  docs/IMPROVE.md
  pr_agent/tools/pr_update_changelog.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#734 Update suggestion content in pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Review effort [1-5]: 1

#736 Doc update
  Usage.md
Labels: documentation, Review effort [1-5]: 1

#735 Add unique_strings function and remove duplicate issues in utils.py
  Usage.md
  pr_agent/algo/utils.py
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#744 Add 'final_update_message' option to control publishing of update messages
  Usage.md
  docs/REVIEW.md
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Review effort [1-5]: 2

#746 Tr/claude3
  Usage.md
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/servers/bitbucket_app.py
  pr_agent/settings/configuration.toml
  requirements.txt
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#747 Refactor litellm_ai_handler.py and update requirements.txt
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  requirements.txt
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#748 Refactor update changelog
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_update_changelog.py
Labels: enhancement, Review effort [1-5]: 3

#758 Fix missing colons in class definitions in pr_reviewer_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: bug_fix, Review effort [1-5]: 1

#759 fixed bug in inline_code_suggestions in review
  pr_agent/tools/pr_reviewer.py
Labels: bug_fix, Review effort [1-5]: 2

#757 Add docs portal
  .github/workflows/docs-ci.yaml
  .gitignore
  Usage.md
  docs/Full_environments.md
  docs/README.md
  docs/REVIEW.md
  docs/TOOLS_GUIDE.md
  docs/docs/CNAME
  docs/docs/assets/favicon.ico
  docs/docs/assets/logo.png
  docs/docs/core-abilities/index.md
  docs/docs/css/custom.css
  docs/docs/index.md
  docs/docs/installation/azure.md
  docs/docs/installation/bitbucket.md
  docs/docs/installation/github.md
  docs/docs/installation/gitlab.md
  docs/docs/installation/index.md
  docs/docs/installation/locally.md
  docs/docs/tools/analyze.md
  docs/docs/tools/ask.md
  docs/docs/tools/ci_feedback.md
  docs/docs/tools/custom_labels.md
  docs/docs/tools/custom_suggestions.md
  docs/docs/tools/describe.md
  docs/docs/tools/documentation.md
  docs/docs/tools/improve.md
  docs/docs/tools/index.md
  docs/docs/tools/similar_code.md
  docs/docs/tools/similar_issues.md
  docs/docs/tools/test.md
  docs/docs/tools/update_changelog.md
  docs/docs/usage-guide/additional_configurations.md
  docs/docs/usage-guide/automations_and_usage.md
  docs/docs/usage-guide/configuration_options.md
  docs/docs/usage-guide/index.md
  docs/docs/usage-guide/introduction.md
  docs/docs/usage-guide/mail_notifications.md
  docs/mkdocs.yml
  docs/overrides/partials/footer.html
Labels: documentation, enhancement, Review effort [1-5]: 2

#760 Tr/readme links
  README.md
  docs/docs/index.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#761 Update README.md with new documentation portal links
  README.md
Labels: documentation, Review effort [1-5]: 1

#762 Update similar_code.md
  docs/docs/tools/similar_code.md
Labels: documentation, Review effort [1-5]: 1

#763 Update README.md with relevant links
  .gitignore
  docs/docs/tools/review.md
Labels: documentation, Review effort [1-5]: 1

#751 Fix URL encoding in Azure DevOps webhook handler
  pr_agent/servers/azuredevops_server_webhook.py
Labels: bug_fix, Review effort [1-5]: 2

#767 readme
  README.md
  docs/docs/index.md
  docs/docs/installation/github.md
  docs/docs/installation/gitlab.md
Labels: documentation, Review effort [1-5]: 1

#768 Hl/incremental review handle edge cases
  pr_agent/git_providers/github_provider.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#769 fix
  pr_agent/tools/pr_reviewer.py
Labels: bug_fix, Review effort [1-5]: 1

#776 Update footer title and improve responsive design in footer.html
  docs/overrides/partials/footer.html
Labels: documentation, enhancement, Review effort [1-5]: 2, Missing SOC2 PR ticket

#779 Update get_pr_labels method to support label updates
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/bitbucket_server_provider.py
  pr_agent/git_providers/codecommit_provider.py
  pr_agent/git_providers/gerrit_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/git_providers/local_git_provider.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Review effort [1-5]: 2

#780 update links
  pr_agent/servers/help.py
  pr_agent/tools/pr_help_message.py
Labels: enhancement, Review effort [1-5]: 1

#786 Added Google Analytics to mkdocs configuration
  docs/mkdocs.yml
Labels: enhancement, Review effort [1-5]: 1

#792 Refactor code in pr_code_suggestions.py
  docs/docs/installation/azure.md
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/tools/pr_code_suggestions.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#793 add corect size logo to the header and adjust title spacing
  docs/docs/assets/logo.svg
  docs/docs/css/custom.css
  docs/mkdocs.yml
Labels: documentation, enhancement, Review effort [1-5]: 2

#795 Enhance AI handler logging and add main PR language attribute to AI h…
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/tools/pr_add_docs.py
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_generate_labels.py
  pr_agent/tools/pr_information_from_user.py
  pr_agent/tools/pr_line_questions.py
  pr_agent/tools/pr_questions.py
  pr_agent/tools/pr_reviewer.py
  pr_agent/tools/pr_update_changelog.py
Labels: enhancement, Review effort [1-5]: 2

#756 can PR be split feature
  README.md
  docs/docs/tools/review.md
  pr_agent/algo/utils.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_reviewer.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#796 Initialize current_labels to empty list if no labels exist in pr_revi…
  pr_agent/tools/pr_reviewer.py
Labels: bug_fix, Review effort [1-5]: 1

#799 Added docs for pr-agent-pro
  docs/docs/installation/index.md
  docs/docs/installation/pr_agent_pro.md
  docs/mkdocs.yml
Labels: documentation, enhancement, Review effort [1-5]: 2

#798 Replace checkmark emojis with tick emojis in documentation
  docs/docs/index.md
Labels: documentation

#781 added support for bedrock/claude3
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/configuration.toml
  requirements.txt
Labels: documentation, enhancement, Review effort [1-5]: 2

#801 Update describe.md: Improve image formatting, restructure content, an…
  docs/docs/tools/describe.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#802 Refactor review.md: Improve image formatting, restructure content, an…
  docs/docs/tools/review.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#803 Refactor improve.md: Improve image formatting, restructure content, a…
  docs/docs/tools/improve.md
  docs/docs/tools/review.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#804 Update build-and-test.yaml
  .github/workflows/build-and-test.yaml
Labels: enhancement, Review effort [1-5]: 1

#805 Update review.md
  docs/docs/tools/review.md
Labels: documentation, Review effort [1-5]: 1

#806 Review vs. Improve tools comparison
  docs/docs/tools/improve.md
Labels: documentation, Review effort [1-5]: 1

#807 Add persistent improve
  docs/docs/tools/improve.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#810 Small update to docs
  docs/docs/tools/describe.md
  docs/docs/tools/review.md
Labels: documentation, Review effort [1-5]: 1

#809 Update build-and-test.yaml
  .github/workflows/build-and-test.yaml
Labels: enhancement, Review effort [1-5]: 1

#811 chore: fix some typos
  docs/docs/installation/azure.md
  docs/docs/usage-guide/automations_and_usage.md
Labels: documentation, Review effort [1-5]: 1

#800 Added `ignore_bot_pr` option
  pr_agent/servers/github_app.py
  pr_agent/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 2, Configuration changes

#814 Tr/pypi
  MANIFEST.in
  README.md
  docs/docs/installation/locally.md
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/cli.py
  pr_agent/cli_pip.py
  pr_agent/servers/__init__.py
  pr_agent/tools/pr_questions.py
  pr_agent/tools/pr_similar_issue.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
Labels: documentation, enhancement, Review effort [1-5]: 2

#815 adjustments to pypi
  docs/docs/installation/locally.md
  pr_agent/cli.py
  pr_agent/cli_pip.py
  pyproject.toml
Labels: enhancement, Review effort [1-5]: 2

#816 Tr/shorter help
  pr_agent/cli.py
  pr_agent/servers/help.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#817 ignore bot
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 2

#821 logs
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 1

#820 add support for gpt-4-turbo-preview model
  pr_agent/algo/__init__.py
Labels: enhancement, Review effort [1-5]: 2

#826 fix: missing requirements.txt on lambda dockerfile
  docker/Dockerfile.lambda
Labels: bug_fix, Review effort [1-5]: 1

#825 Refactor markdown image syntax and enhance documentation presentation
  .github/workflows/docs-ci.yaml
  docs/docs/core-abilities/index.md
  docs/docs/css/custom.css
  docs/docs/index.md
  docs/docs/installation/pr_agent_pro.md
  docs/docs/tools/analyze.md
  docs/docs/tools/ask.md
  docs/docs/tools/ci_feedback.md
  docs/docs/tools/custom_labels.md
  docs/docs/tools/custom_suggestions.md
  docs/docs/tools/describe.md
  docs/docs/tools/documentation.md
  docs/docs/tools/improve.md
  docs/docs/tools/review.md
  docs/docs/tools/similar_code.md
  docs/docs/tools/similar_issues.md
  docs/docs/tools/test.md
  docs/docs/tools/update_changelog.md
  docs/docs/usage-guide/configuration_options.md
  docs/docs/usage-guide/mail_notifications.md
  docs/mkdocs.yml
Labels: documentation, enhancement, Review effort [1-5]: 2

#829 Update github.md
  docs/docs/installation/github.md
Labels: documentation, Review effort [1-5]: 1

#828 Improve trigger condition in github actions
  docs/docs/installation/github.md
  pr_agent/servers/github_action_runner.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#831 docs: Refine project description and reorganize documentation links i…
  README.md
Labels: documentation, Review effort [1-5]: 1

#832 refine help
  pr_agent/tools/pr_help_message.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#833 docs: Add "Improve Component" tool documentation and update related g…
  docs/docs/tools/analyze.md
  docs/docs/tools/documentation.md
  docs/docs/tools/improve_component.md
  docs/docs/tools/index.md
  docs/docs/tools/test.md
  docs/mkdocs.yml
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 2
