Repository qodo-ai/pr-agent, pull requests merged in 2024-02, with the labels that each got.

#636 moving the 'improve' command to turbo mode, with auto_extended=true
  pr_agent/algo/__init__.py
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Review effort [1-5]: 3

#637 pr-actions
  README.md
Labels: documentation, Review effort [1-5]: 1

#638 insert_br_after_x_chars
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  pr_agent/algo/types.py
  pr_agent/algo/utils.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/bitbucket_server_provider.py
  pr_agent/git_providers/codecommit_provider.py
  pr_agent/git_providers/gerrit_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/git_providers/local_git_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  tests/unittest/test_codecommit_provider.py
  tests/unittest/test_convert_to_markdown.py
  tests/unittest/test_find_line_number_of_relevant_line_in_file.py
Labels: enhancement, Review effort [1-5]: 3

#639 Tr/describe bullets
  pr_agent/tools/pr_description.py
  tests/unittest/test_convert_to_markdown.py
Labels: Bug fix, Tests, Review effort [1-5]: 2

#640 publish_output fix
  Usage.md
Labels: documentation, Review effort [1-5]: 1

#641 auto approval feature
  README.md
  docs/REVIEW.md
  pr_agent/agent/pr_agent.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Review effort [1-5]: 4

#642 readme cleaning
  INSTALL.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#643 DOCS: add table to files changes action
  docs/DESCRIBE.md
Labels: documentation, Review effort [1-5]: 1

#644 Tr/parallel calls
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Review effort [1-5]: 3

#646 Hl/pr review table
  docs/REVIEW.md
  pr_agent/algo/utils.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/bitbucket_server_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_convert_to_markdown.py
  tests/unittest/test_load_yaml.py
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#651 insert_br_after_x_chars can already handle code
  pr_agent/tools/pr_description.py
Labels: enhancement, Review effort [1-5]: 2, Possible security concern

#654 add pull_request event triggers for github action
  pr_agent/servers/github_action_runner.py
Labels: enhancement, Review effort [1-5]: 1

#655 Add AI disclaimer fields to configuration.toml
  pr_agent/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 1, Configuration changes

#653 add loading comment to /improve
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Review effort [1-5]: 2

#650 Support Azure Inline Comment
  pr_agent/git_providers/azuredevops_provider.py
Labels: enhancement, Review effort [1-5]: 3

#649 filter events to align with pr-agent's setting
  INSTALL.md
Labels: enhancement, Review effort [1-5]: 1

#659 no html bitbucket
  pr_agent/algo/utils.py
Labels: enhancement, Review effort [1-5]: 2

#660 Add logging context to command execution in pr_agent.py
  pr_agent/agent/pr_agent.py
Labels: enhancement, Review effort [1-5]: 2

#667 azure webhook
  Usage.md
  docker/Dockerfile
  pr_agent/algo/utils.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/servers/azuredevops_server_webhook.py
  pr_agent/settings/.secrets_template.toml
  pr_agent/tools/pr_description.py
Labels: documentation, enhancement, Review effort [1-5]: 4, Possible security concern

#665 Update README and documentation with new CI Feedback tool
  README.md
  docs/CI_FEEDBACK.md
  docs/TOOLS_GUIDE.md
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#661 Hl/ask line
  docs/ASK.md
  pr_agent/agent/pr_agent.py
  pr_agent/algo/git_patch_processing.py
  pr_agent/config_loader.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/bitbucket_server_provider.py
  pr_agent/git_providers/codecommit_provider.py
  pr_agent/git_providers/gerrit_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/servers/github_action_runner.py
  pr_agent/servers/github_app.py
  pr_agent/servers/gitlab_webhook.py
  pr_agent/settings/pr_line_questions_prompts.toml
  pr_agent/tools/pr_line_questions.py
Labels: documentation, enhancement, Review effort [1-5]: 4

#669 readme
  README.md
  docs/ASK.md
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#673 Added PRHelpMessage to command execution in pr_agent.py
  pr_agent/agent/pr_agent.py
  pr_agent/tools/pr_help_message.py
Labels: enhancement, Review effort [1-5]: 2

#676 bitbucket code suggestions
  pr_agent/algo/utils.py
  tests/unittest/test_parse_code_suggestion.py
Labels: enhancement, Review effort [1-5]: 2

#677 help improved
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_help_message.py
Labels: enhancement, Review effort [1-5]: 3

#678 Tr/help invoke
  README.md
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_help_message.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#666 Add Az Devops managed identity support
  Usage.md
  docs/Full_environments.md
  pr_agent/git_providers/azuredevops_provider.py
  requirements.txt
Labels: enhancement, Review effort [1-5]: 2

#679 Refactor reaction handling in GitHub provider and update help text
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_questions.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#682 Add a note about change the target for Gitlab install
  INSTALL.md
Labels: documentation, Review effort [1-5]: 1

#683 Tr/fixes
  README.md
  Usage.md
  docs/CI_FEEDBACK.md
  pr_agent/servers/azuredevops_server_webhook.py
  pr_agent/servers/gitlab_webhook.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_help_message.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#684 Tr/reduce number of calls
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/utils.py
Labels: enhancement, Review effort [1-5]: 3

#686 Tr/reduce number of calls
  pr_agent/git_providers/utils.py
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 2

#687 Update README.md to include Azure DevOps in supported platforms
  README.md
Labels: enhancement, Review effort [1-5]: 1

#694 Adds an option to ignore PR opens by regex matching
  pr_agent/servers/github_app.py
  pr_agent/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 2

#696 Refactor GitHup App
  pr_agent/git_providers/github_provider.py
  pr_agent/servers/github_app.py
  pr_agent/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 2

#701 Change github app startup logic to support gunicorj
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 2

#707 Introduced collapsible file list threshold as a constant
  pr_agent/tools/pr_description.py
Labels: enhancement, Review effort [1-5]: 2

#708 Refactor logging
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/cli.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/utils.py
  pr_agent/log/__init__.py
  pr_agent/servers/github_app.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_help_message.py
  pr_agent/tools/pr_questions.py
  pr_agent/tools/pr_reviewer.py
  pr_agent/tools/pr_update_changelog.py
Labels: documentation, enhancement, bug_fix, Review effort [1-5]: 2

#695 Add support for analytics file
  pr_agent/log/__init__.py
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 2

#709 adjustment
  pr_agent/git_providers/github_provider.py
  pr_agent/tools/pr_description.py
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#712 Tr/review tweaks
  pr_agent/algo/utils.py
  tests/unittest/test_convert_to_markdown.py
Labels: enhancement, Review effort [1-5]: 2

#715 small log improvement
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 1

#716 Add analytics logging
  pr_agent/agent/pr_agent.py
  pr_agent/log/__init__.py
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 2

#717 Add documentation for 'ignore_pr_titles' parameter in Usage.md
  Usage.md
Labels: documentation, Review effort [1-5]: 1

#719 Ok/identity provider
  pr_agent/identity_providers/__init__.py
  pr_agent/identity_providers/default_identity_provider.py
  pr_agent/identity_providers/identity_provider.py
  pr_agent/servers/bitbucket_app.py
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 3

#721 Identity provider
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 2

#723 some fixes
  README.md
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_generate_labels.py
  pr_agent/tools/pr_help_message.py
  pr_agent/tools/pr_reviewer.py
  pr_agent/tools/pr_update_changelog.py
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#714 improve tweaks
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Review effort [1-5]: 2

#725 get_log_context
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 2

#727 log event
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 1

#728 Update IMPROVE.md
  docs/IMPROVE.md
Labels: documentation, Review effort [1-5]: 1
