Repository qodo-ai/pr-agent, pull requests merged in 2024-06, with the labels that each got.

#937 Optimize document table format
  docs/docs/finetuning_benchmark/index.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#933 Fix some server implementations not properly logging context
  pr_agent/servers/azuredevops_server_webhook.py
  pr_agent/servers/bitbucket_server_webhook.py
  pr_agent/servers/gitlab_webhook.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#938 Add documentation for PR-Agent code fine-tuning benchmark and update …
  docs/docs/finetuning_benchmark/index.md
Labels: documentation, Review effort [1-5]: 2

#939 Disable final update message when auto_describe is enabled in GitHub …
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/servers/github_action_runner.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#940 Add PR evaluation prompt and link to fine-tuning benchmark documentation
  docs/docs/finetuning_benchmark/index.md
  pr_agent/settings/pr_evaluate_prompt_response.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#941 Ok/gitlab fix
  pr_agent/servers/gitlab_webhook.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#942 Update Python code formatting, configuration loading, and local model additions
  docs/docs/usage-guide/introduction.md
  pr_agent/agent/pr_agent.py
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/base_ai_handler.py
  pr_agent/algo/ai_handlers/langchain_ai_handler.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/algo/ai_handlers/openai_ai_handler.py
  pr_agent/algo/file_filter.py
  pr_agent/algo/utils.py
  pr_agent/cli.py
  pr_agent/config_loader.py
  pr_agent/git_providers/__init__.py
  pr_agent/servers/github_action_runner.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#944 handle_push_trigger for gitlab
  docs/docs/tools/review.md
  pr_agent/servers/gitlab_webhook.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Review effort [1-5]: 3, Configuration changes

#946 gitlab push_commands will work
  pr_agent/servers/gitlab_webhook.py
  pr_agent/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 2, Configuration changes

#947 gitlab push_commands
  docs/docs/usage-guide/automations_and_usage.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#951 committable checbox
  README.md
  docs/docs/tools/improve.md
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#950 update LangChainOpenAIHandler for langchain version 0.2 and read openai_api_base
  pr_agent/algo/ai_handlers/langchain_ai_handler.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#955 Github: work in background
  pr_agent/servers/github_app.py
Labels: enhancement, Review effort [1-5]: 2

#954 Update PR review prompts and terminology for clarity and consistency
  docs/docs/tools/review.md
  pr_agent/algo/utils.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_convert_to_markdown.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#965 Tr/reviewer
  pr_agent/algo/utils.py
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: documentation, enhancement, Bug fix, Review effort [1-5]: 3

#966 Tr/ignore
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/algo/file_filter.py
  pr_agent/algo/language_handler.py
  pr_agent/algo/utils.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/settings/ignore.toml
  tests/unittest/test_convert_to_markdown.py
Labels: documentation, enhancement, Review effort [1-5]: 4

#964 Support models: Anthropic Claude 3 on Vertex AI
  pr_agent/algo/__init__.py
  requirements.txt
Labels: enhancement, Review effort [1-5]: 2, dependencies

#967 Fix ModuleNotFoundError of Vertex AI
  requirements.txt
Labels: Review effort [1-5]: 1, dependencies

#972 Overall_success
  pr_agent/git_providers/azuredevops_provider.py
Labels: Bug fix, Review effort [1-5]: 1

#974 repetition_penalty
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: Bug fix, Review effort [1-5]: 1

#976 get_changlog_file
  pr_agent/tools/pr_update_changelog.py
Labels: Bug fix, Review effort [1-5]: 1

#975 identify_image_in_comment
  pr_agent/tools/pr_questions.py
Labels: Bug fix, Review effort [1-5]: 1

#978 Add self-review checkbox functionality to improve tool and update doc…
  README.md
  docs/docs/tools/improve.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#980 mkdocs
  docs/docs/css/custom.css
  docs/docs/overview/data_privacy.md
  docs/docs/overview/index.md
  docs/docs/overview/pr_agent_pro.md
  docs/docs/tools/similar_issues.md
  docs/mkdocs.yml
Labels: documentation, enhancement, Review effort [1-5]: 2

#981 mkdocs
  docs/docs/index.md
  docs/mkdocs.yml
Labels: documentation

#983 Support running GitHub App using gunicorn, adjust Dockerfile accordingly
  docker/Dockerfile
  pr_agent/servers/gunicorn_config.py
  requirements.txt
Labels: enhancement, Review effort [1-5]: 3, Configuration changes

#984 Tr/cache git provider
  pr_agent/git_providers/__init__.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/utils.py
  pr_agent/servers/github_app.py
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#986 Add `is_auto_command` config check to conditionally publish output an…
  pr_agent/servers/github_app.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Review effort [1-5]: 2, Configuration changes

#989 Update requirements.txt
  requirements.txt
Labels: Review effort [1-5]: 1, dependencies

#990 feat: claude 3.5 sonnet support
  pr_agent/algo/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#995 fix: update prompt key from `suggestion_content` to `suggestion_summary` in code suggestions
  pr_agent/settings/pr_code_suggestions_reflect_prompts.toml
Labels: Bug fix, Review effort [1-5]: 1

#998 Add gemini support for pr-agent
  pr_agent/algo/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#1000 feat: Support Anthropic Calude 3.5 Sonnet on Vertex AI
  pr_agent/algo/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#1006 s
  docs/docs/usage-guide/additional_configurations.md
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/servers/github_app.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#1004 Tr/large pr
  docs/docs/tools/describe.md
  pr_agent/algo/pr_processing.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
Labels: enhancement, Bug fix, Other, Review effort [1-5]: 4

#1009 fixes
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Other, Review effort [1-5]: 2

#1005 Centralize PR Review Title Definition
  pr_agent/algo/utils.py
  pr_agent/git_providers/github_provider.py
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_convert_to_markdown.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#1014 Tr/description
  pr_agent/algo/pr_processing.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_add_docs.py
  pr_agent/tools/pr_description.py
Labels: enhancement, Tests, Review effort [1-5]: 3
