Repository qodo-ai/pr-agent, pull requests merged in 2024-05, with the labels that each got.

#887 Tr/branding
  pr_agent/algo/utils.py
  pr_agent/git_providers/git_provider.py
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_help_message.py
  pr_agent/tools/pr_questions.py
  pr_agent/tools/pr_reviewer.py
  pr_agent/tools/pr_update_changelog.py
  tests/unittest/test_convert_to_markdown.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#889 privacy policy for chrome extension
  README.md
Labels: Review effort [1-5]: 1

#892 Update configuration_options.md
  docs/docs/usage-guide/configuration_options.md
Labels: Review effort [1-5]: 1

#893 Tr/readme3
  docs/docs/tools/describe.md
  docs/docs/tools/improve.md
  docs/docs/tools/review.md
  docs/docs/usage-guide/configuration_options.md
Labels: Review effort [1-5]: 2

#894 Tr/self reflect
  pr_agent/config_loader.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_code_suggestions_reflect_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 3

#895 self-reflection documentation
  README.md
  docs/docs/tools/improve.md
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 2

#897 Tr/self reflect
  README.md
  docs/docs/tools/improve.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 2

#898 Tr/self reflect
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_code_suggestions_reflect_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 3

#901 Add new GPT-4o models and update tiktoken to 0.7.0
  pr_agent/algo/__init__.py
  requirements.txt
Labels: Review effort [1-5]: 2

#902 Properly fetch changed files
  pr_agent/algo/utils.py
  pr_agent/git_providers/azuredevops_provider.py
Labels: Bug fix, Review effort [1-5]: 3

#903 Update README.md
  README.md
Labels: Review effort [1-5]: 1

#904 Add documentation for PR-Agent Chrome Extension and update mkdocs.yml…
  docs/docs/chrome-extension/index.md
  docs/mkdocs.yml
Labels: documentation, Review effort [1-5]: 2

#905 Add roadmap section to Chrome Extension documentation with visual pre…
  docs/docs/chrome-extension/index.md
Labels: Review effort [1-5]: 1

#910 Tr/show config
  docs/docs/usage-guide/configuration_options.md
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
  pr_agent/tools/pr_update_changelog.py
Labels: Review effort [1-5]: 3

#911 Update configuration_options.md to include tip on showing relevant co…
  pr_agent/algo/utils.py
Labels: Review effort [1-5]: 2

#912 Tr/show config
  README.md
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_questions.py
  pr_agent/tools/pr_reviewer.py
Labels: Review effort [1-5]: 3

#913 Update default setting of `final_update_message` to false in describe…
  docs/docs/tools/describe.md
  pr_agent/settings/configuration.toml
Labels: documentation, Review effort [1-5]: 1, Configuration changes

#916 Chrome Extension readme
  docs/docs/chrome-extension/index.md
Labels: documentation, Review effort [1-5]: 2

#918 protections
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/language_extensions.toml
Labels: enhancement, Review effort [1-5]: 2, error handling

#926 docs: update additional_configurations.md
  docs/docs/usage-guide/additional_configurations.md
Labels: documentation, Review effort [1-5]: 1

#931 Add logging for skipping non-code files in GitHub provider
  pr_agent/git_providers/github_provider.py
Labels: enhancement, Review effort [1-5]: 1, logging

#928 Bitbucket Server Provider Fixes
  pr_agent/git_providers/bitbucket_server_provider.py
Labels: Bug fix, Review effort [1-5]: 3

#935 Add documentation for PR-Agent code fine-tuning benchmark and update …
  docs/docs/finetuning_benchmark/index.md
  docs/mkdocs.yml
Labels: documentation, Review effort [1-5]: 2

#936 Update README.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#932 Bitbucket server filter out globally ignored files before attempting diff
  .gitignore
  pr_agent/git_providers/bitbucket_server_provider.py
Labels: enhancement, Review effort [1-5]: 2, logging
