Repository qodo-ai/pr-agent, pull requests merged in 2024-11, with the labels that each got.

#1332 Merge branch 'main' of https://github.com/ryanzll/pr-agent
  pr_agent/algo/ai_handlers/openai_ai_handler.py
Labels: Review effort [1-5]: 2

#1337 Update additional_configurations.md
  docs/docs/usage-guide/additional_configurations.md
Labels: Review effort [1-5]: 1

#1338 Add support for processing diffs without line numbers in code suggest…
  docs/docs/core-abilities/self_reflection.md
  docs/docs/tools/improve.md
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_code_suggestions_reflect_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 3

#1331 Add configuration option to control publish of no code suggestions message
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 2

#1341 Hl/docs tickets
  README.md
  docs/docs/core-abilities/fetching_ticket_context.md
  docs/docs/core-abilities/index.md
  docs/docs/tools/review.md
  docs/mkdocs.yml
Labels: Review effort [1-5]: 2

#1342 update docs
  docs/docs/core-abilities/fetching_ticket_context.md
  docs/docs/core-abilities/index.md
Labels: Review effort [1-5]: 1

#1343 Update automations_and_usage.md
  docs/docs/usage-guide/automations_and_usage.md
Labels: Review effort [1-5]: 1

#1348 Add focus_only_on_problems setting for targeted code suggestions
  README.md
  docs/docs/tools/improve.md
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 2

#1351 Fixed mkdocs emoji configuration after pre-commit error
  .github/workflows/pre-commit.yml
  docs/mkdocs.yml
Labels: Review effort [1-5]: 1

#1354 Tr/3 way prs
  pr_agent/algo/git_patch_processing.py
  pr_agent/git_providers/github_provider.py
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 3

#1359 Refactor `is_bot_user` function to improve actor type handling
  pr_agent/servers/bitbucket_app.py
Labels: Review effort [1-5]: 2

#1362 docs: add note about $CI_SERVER_FQDN variable in GitLab CI/CD pipeline
  docs/docs/installation/gitlab.md
Labels: Review effort [1-5]: 1

#1367 Enable focus_only_on_problems mode by default in configuration and up…
  README.md
  docs/docs/tools/improve.md
  pr_agent/settings/configuration.toml
Labels: Review effort [1-5]: 1

#1355 use a more modern package
  pr_agent/git_providers/bitbucket_server_provider.py
Labels: Review effort [1-5]: 2

#1369 Tr/committable comments
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/bitbucket_server_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
Labels: Review effort [1-5]: 3

#1373 Improve logging and error handling in Azure DevOps provider for code …
  pr_agent/git_providers/azuredevops_provider.py
Labels: Review effort [1-5]: 2
