Repository qodo-ai/pr-agent, pull requests merged in 2024-04, with the labels that each got.

#834 analytics
  docs/mkdocs.yml
  docs/overrides/main.html
  docs/overrides/partials/integrations/analytics/custom.html
Labels: enhancement, Review effort [1-5]: 2

#836 feat: allows ollama usage
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: enhancement, Review effort [1-5]: 2

#837 feat: add persistent comment option for PR descriptions
  docs/docs/tools/describe.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_description.py
Labels: enhancement, Review effort [1-5]: 2

#838 TokenEncoder
  pr_agent/algo/token_handler.py
  pr_agent/algo/utils.py
Labels: enhancement, Review effort [1-5]: 2

#839 Update additional_configurations.md
  docs/docs/usage-guide/additional_configurations.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#840 readme
  README.md
  docs/docs/index.md
  docs/docs/installation/index.md
  docs/docs/usage-guide/automations_and_usage.md
  docs/mkdocs.yml
Labels: documentation, Review effort [1-5]: 2

#841 readme
  docs/docs/index.md
  docs/docs/tools/analyze.md
  docs/docs/tools/help.md
  docs/docs/tools/index.md
  docs/docs/usage-guide/index.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#842 readme
  docs/docs/tools/describe.md
  docs/docs/tools/help.md
  docs/docs/usage-guide/mail_notifications.md
  docs/mkdocs.yml
  pr_agent/tools/pr_code_suggestions.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#843 Fix Broken URL in README.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#844 readme
  docs/docs/tools/improve.md
  docs/docs/tools/review.md
  docs/docs/usage-guide/configuration_options.md
  pr_agent/algo/utils.py
  pr_agent/servers/help.py
  tests/unittest/test_clip_tokens.py
Labels: enhancement, Review effort [1-5]: 2

#845 Update docs readme
  docs/README.md
Labels: documentation, Review effort [1-5]: 1

#846 readme
  docs/docs/index.md
Labels: documentation, Review effort [1-5]: 1

#848 Tr/readme
  pr_agent/algo/utils.py
  pr_agent/git_providers/github_provider.py
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_clip_tokens.py
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#851 Failed to review PR: name 'is_valid_file' is not defined
  pr_agent/git_providers/codecommit_provider.py
Labels: bug_fix, Review effort [1-5]: 1

#854 add support for gpt-4-turbo model
  pr_agent/algo/__init__.py
Labels: enhancement, Review effort [1-5]: 1

#853 feat: set review data to github actions output
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/algo/utils.py
  pr_agent/servers/github_action_runner.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_github_action_output.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#858 Handle OPENAI_KEY not set error in github_action_runner.py
  pr_agent/servers/github_action_runner.py
Labels: bug_fix, Review effort [1-5]: 2

#859 Tr/image
  README.md
  docs/docs/tools/ask.md
  pr_agent/algo/ai_handlers/base_ai_handler.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/servers/github_app.py
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_questions.py
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#860 ask
  docs/docs/tools/ask.md
Labels: documentation, Review effort [1-5]: 1

#862 ask
  README.md
  docs/docs/tools/ask.md
Labels: documentation, Review effort [1-5]: 1

#863 Add repo url to docs
  docs/mkdocs.yml
Labels: documentation, enhancement, Review effort [1-5]: 1

#864 Example usage
  docs/docs/tools/describe.md
Labels: documentation, Review effort [1-5]: 1

#865 Tr/readme
  .pr_agent.toml
  docs/docs/tools/describe.md
  docs/docs/tools/improve.md
  docs/docs/tools/review.md
  docs/docs/usage-guide/automations_and_usage.md
  docs/docs/usage-guide/configuration_options.md
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
Labels: documentation, enhancement, Review effort [1-5]: 1

#870 Replace `summarize_mode` with `commitable_code_suggestions_mode` in p…
  pr_agent/settings/pr_code_suggestions_prompts.toml
Labels: enhancement, Review effort [1-5]: 1

#871 Tr/readme
  docs/docs/tools/ask.md
  docs/docs/tools/describe.md
  docs/docs/tools/improve.md
  docs/docs/tools/review.md
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/servers/github_app.py
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#872 ## Example usage
  docs/docs/tools/analyze.md
  docs/docs/tools/ci_feedback.md
  docs/docs/tools/custom_labels.md
  docs/docs/tools/custom_suggestions.md
  docs/docs/tools/documentation.md
  docs/docs/tools/improve.md
  docs/docs/tools/improve_component.md
  docs/docs/tools/similar_issues.md
  docs/docs/tools/test.md
  docs/docs/tools/update_changelog.md
Labels: documentation, Review effort [1-5]: 2

#873 docs: Add option to disable automatic CI feedback in configuration
  docs/docs/tools/ci_feedback.md
Labels: documentation, Review effort [1-5]: 1

#876 Fix duplicate assignment of replicate_key in LiteLLMAIHandler
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: Bug fix, Review effort [1-5]: 1

#877 Add Groq Llama3 support
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/.secrets_template.toml
Labels: enhancement, Review effort [1-5]: 2

#880 chore: update GPT3.5 models
  pr_agent/algo/__init__.py
Labels: enhancement, Review effort [1-5]: 2
