Repository qodo-ai/pr-agent, pull requests merged in 2024-08, with the labels that each got.

#1081 Bitbucket Server fix inline comments and reading .pr_agent.toml
  pr_agent/git_providers/bitbucket_server_provider.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#1079 Use code blocks instead of suggestion blocks for Bitbucket Server multi-line suggestions
  pr_agent/git_providers/bitbucket_server_provider.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1083 update dependencies to fix various high/critical security vulnerabilies
  docker/Dockerfile
  requirements.txt
Labels: Bug fix, dependencies

#1073 Improve response cleaning
  pr_agent/algo/utils.py
Labels: enhancement, Review effort [1-5]: 1

#1090 Update test_convert_to_markdown.py
  tests/unittest/test_convert_to_markdown.py
  tests/unittest/test_load_yaml.py
Labels: Tests, Review effort [1-5]: 1

#1091 patch and prompt improvements
  docker/Dockerfile
  pr_agent/algo/git_patch_processing.py
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_code_suggestions_reflect_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: documentation, enhancement, Review effort [1-5]: 3

#1092 Tr/gitlab pipeline
  README.md
  docs/docs/installation/gitlab.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#1093 Escape HTML tags in suggestion summaries in pr_code_suggestions.py
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#1095 Tr/code cov
  .github/workflows/code_coverage.yaml
  requirements.txt
Labels: enhancement, Tests, Review effort [1-5]: 2

#1103 Fix pr_processing.get_pr_multi_diffs
  pr_agent/algo/pr_processing.py
Labels: Bug fix, Review effort [1-5]: 1

#1100 Clarification on webhook URL for Gitlab
  docs/docs/installation/gitlab.md
Labels: documentation, Review effort [1-5]: 1

#1102 Fix LangChainOpenAIHandler for Azure
  pr_agent/algo/ai_handlers/langchain_ai_handler.py
  requirements.txt
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1106 protections
  pr_agent/tools/pr_description.py
Labels: enhancement, Review effort [1-5]: 2

#1107 protections
  pr_agent/algo/token_handler.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1108 Tr/azure pipeline
  README.md
  docs/docs/installation/azure.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#1114 Tr/patch extra lines before and after
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/algo/__init__.py
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  pr_agent/git_providers/utils.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  tests/unittest/test_extend_patch.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#1115 Fix incorrect logic for extending patch size beyond original file length
  pr_agent/algo/git_patch_processing.py
Labels: Bug fix, Review effort [1-5]: 2

#1116 Tr/patch extra lines before and after
  pr_agent/algo/git_patch_processing.py
Labels: Bug fix, Review effort [1-5]: 2

#1117 Add missing newline in extended patch and remove trailing whitespace
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  tests/unittest/test_extend_patch.py
Labels: enhancement, Review effort [1-5]: 1

#1118 Improve Bitbucket patch diff handling
  pr_agent/algo/git_patch_processing.py
  pr_agent/git_providers/bitbucket_provider.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#1119 Hl/limit long comments
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1123 Add app_name to log_context in Bitbucket and GitLab webhook handlers
  pr_agent/servers/bitbucket_app.py
  pr_agent/servers/gitlab_webhook.py
Labels: enhancement, Review effort [1-5]: 1

#1124 protections
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Review effort [1-5]: 2

#1125 Tr/err protections
  pr_agent/algo/file_filter.py
  pr_agent/git_providers/bitbucket_provider.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1128 Tr/err_protections
  pr_agent/algo/language_handler.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/servers/bitbucket_app.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1130 Tr/err protections
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/algo/utils.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1127 Fix base url not being passed through github_provider class correctly
  pr_agent/git_providers/github_provider.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1132 Add error handling for missing GitLab URL and improve inline comment …
  pr_agent/git_providers/gitlab_provider.py
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#1133 Add error handling for empty diff files in utils.py and optimize file…
  pr_agent/algo/utils.py
  pr_agent/git_providers/bitbucket_provider.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1134 Tr/err protections
  pr_agent/algo/utils.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1135 fix html escaping
  pr_agent/algo/utils.py
Labels: Bug fix, Review effort [1-5]: 1

#1138 Add 'only_markdown' parameter to emphasize_header call in utils.py fo…
  pr_agent/algo/utils.py
Labels: enhancement, Review effort [1-5]: 1

#1141 Add documentation for PR-Chat feature in PR-Agent Chrome extension
  docs/docs/chrome-extension/index.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#1142 Add security and privacy section to Chrome extension documentation
  docs/docs/chrome-extension/index.md
Labels: documentation, enhancement

#1126 update litellm library
  requirements.txt
Labels: enhancement, Review effort [1-5]: 1

#1151 Add 'original_suggestion' parameter to publish_inline_comment methods…
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/bitbucket_server_provider.py
  pr_agent/git_providers/codecommit_provider.py
  pr_agent/git_providers/gerrit_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/git_providers/local_git_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Review effort [1-5]: 2

#1153 Tr/protections2
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/servers/github_polling.py
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#1155 Update index.md
  docs/docs/chrome-extension/index.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#1156 Tr/dynamic context
  pr_agent/algo/git_patch_processing.py
  pr_agent/settings/configuration.toml
  tests/unittest/test_extend_patch.py
Labels: enhancement, Review effort [1-5]: 3

#1159 Tr/patches
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: enhancement, Review effort [1-5]: 2

#1161 fix: remove CI_MERGE_REQUEST_STATE as is not a Gitlab variable
  docs/docs/installation/gitlab.md
Labels: documentation, Bug fix, Review effort [1-5]: 1

#1145 Add and document abilty to use LiteLLM Logging Observability tools
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/agent/pr_agent.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 3

#1165 feat: handle gitlab MR draft status
  pr_agent/servers/gitlab_webhook.py
Labels: enhancement, Review effort [1-5]: 2

#1170 Update PR code suggestions prompts
  pr_agent/settings/pr_code_suggestions_prompts.toml
Labels: enhancement, Review effort [1-5]: 2

#1174 Tr/protections2
  pr_agent/servers/github_polling.py
Labels: Other

#1175 Tr/protections2
  pr_agent/algo/utils.py
  pr_agent/settings/pr_description_prompts.toml
  tests/unittest/test_load_yaml.py
  tests/unittest/test_try_fix_yaml.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1177 feat: keep manual comments working when commenting draft MRs
  pr_agent/servers/gitlab_webhook.py
Labels: enhancement, Review effort [1-5]: 1

#1179 fix: handle deleted files in git patch processing and update section header logic
  pr_agent/algo/git_patch_processing.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1163 Ensure asyncio event queue is drained prior to CLI termination
  pr_agent/cli.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1184 checking for publish_output in the suggestions tool exception handler
  pr_agent/tools/pr_code_suggestions.py
Labels: Bug fix, Review effort [1-5]: 2

#1189 fix: change deprecated timeout parameter for litellm
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: Bug fix, Review effort [1-5]: 1

#1185 Update pr_update_changelog.py to include "[skip ci]" so pipeline is n…
  pr_agent/tools/pr_update_changelog.py
Labels: enhancement, Review effort [1-5]: 1

#1191 Fixing code suggestions being published when publish ouput is false
  pr_agent/tools/pr_code_suggestions.py
Labels: Bug fix, Review effort [1-5]: 2
