Repository qodo-ai/pr-agent, pull requests merged in 2024-10, with the labels that each got.

#1263 feat: add dual publishing mode for PR code suggestions
  docs/docs/tools/improve.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#1264 dual publishing mode
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Review effort [1-5]: 2

#1267 feat: enhance PR processing logic across GitLab, GitHub, and Bitbucket
  pr_agent/servers/bitbucket_app.py
  pr_agent/servers/github_app.py
  pr_agent/servers/gitlab_webhook.py
Labels: enhancement, Review effort [1-5]: 3

#1271 docs: add links to technical blogs on LLMs and coding tasks in core a…
  docs/docs/core-abilities/index.md
Labels: documentation, enhancement, Review effort [1-5]: 1

#1272 Tr/warning on bad config
  pr_agent/git_providers/utils.py
  pr_agent/settings/pr_code_suggestions_prompts.toml
Labels: enhancement, Review effort [1-5]: 3

#1276 docs: update improve.md with folding suggestions feature and add conf…
  docs/docs/tools/improve.md
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#1279 feat: add support for O1 model by combining system and user prompt
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: enhancement, Review effort [1-5]: 2

#1280 Update footer links and branding from CodiumAI to Qodo
  docs/docs/assets/favicon.ico
  docs/docs/assets/logo.svg
  docs/docs/assets/logo_.png
  docs/overrides/partials/footer.html
Labels: documentation, Review effort [1-5]: 1

#1282 Tr/ticket review
  README.md
  docs/docs/index.md
  docs/docs/overview/index.md
  docs/docs/overview/pr_agent_pro.md
  docs/docs/tools/review.md
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
  pr_agent/tools/ticket_pr_compliance_check.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#1283 Update README.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#1289 fix: handle missing issue body and improve error logging in ticket co…
  pr_agent/tools/ticket_pr_compliance_check.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1291 Tr/server
  pr_agent/git_providers/github_provider.py
Labels: enhancement, Review effort [1-5]: 3, error handling

#1292 Tr/server
  docs/docs/installation/github.md
  docs/docs/installation/locally.md
  docs/docs/installation/pr_agent_pro.md
Labels: documentation, Review effort [1-5]: 2

#1290 support more types of github ticket url / references
  pr_agent/tools/ticket_pr_compliance_check.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1295 fix: correct model type extraction for O1 model handling
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: bug_fix, Review effort [1-5]: 2

#1298 docs: update pr_help_prompts.toml with project name change and format…
  pr_agent/settings/pr_help_prompts.toml
Labels: documentation, Review effort [1-5]: 1

#1299 disable publishing labels by default
  README.md
  docs/docs/tools/describe.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_description.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#1303 Update atlassian-connect.json
  pr_agent/servers/atlassian-connect.json
Labels: enhancement, Review effort [1-5]: 2, Configuration changes

#1305 fix typos in documents
  docs/docs/installation/index.md
  docs/docs/overview/pr_agent_pro.md
  docs/docs/tools/custom_labels.md
Labels: documentation, Review effort [1-5]: 1

#1306 Tr/help
  docker/Dockerfile
  docs/chroma_db.zip
  pr_agent/settings/pr_help_prompts.toml
  pr_agent/tools/pr_help_message.py
  requirements.txt
Labels: enhancement, Review effort [1-5]: 3, dependencies

#1309 Tr/suggestion tracking
  README.md
  docs/docs/tools/improve.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_help_message.py
Labels: Review effort [1-5]: 2

#1311 Add PRDescriptionHeader enum for consistent "Changes walkthrough" usa…
  pr_agent/algo/utils.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/tools/pr_description.py
Labels: Review effort [1-5]: 2

#1307 Gitlab docs improved; gitlab webhook secret config standardization
  docs/docs/installation/gitlab.md
  pr_agent/settings/.secrets_template.toml
Labels: Review effort [1-5]: 2

#1321 Self-Reflection small fix
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 2

#1325 update bitbucket-pipelines.yml filename in installation
  docs/docs/installation/bitbucket.md
Labels: Review effort [1-5]: 1

#1326 Add certifi==2024.8.30 to requirements.txt
  requirements.txt
Labels: Review effort [1-5]: 1
