Repository qodo-ai/pr-agent, pull requests merged in 2024-12, with the labels that each got.

#1375 Update Google Tag Manager ID in custom analytics integration
  docs/overrides/partials/integrations/analytics/custom.html
Labels: Review effort [1-5]: 1

#1376 Add publish_output_progress config support to AzureDevOps, BitBucket and Gitlab providers
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/gitlab_provider.py
Labels: Review effort [1-5]: 2

#1379 Add disable_auto_feedback configuration option to control automatic feedback
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/servers/azuredevops_server_webhook.py
  pr_agent/servers/bitbucket_app.py
  pr_agent/servers/bitbucket_server_webhook.py
  pr_agent/servers/github_app.py
  pr_agent/servers/gitlab_webhook.py
  pr_agent/settings/configuration.toml
Labels: Review effort [1-5]: 2

#1380 Update fetching_ticket_context.md
  docs/docs/core-abilities/fetching_ticket_context.md
Labels: Review effort [1-5]: 1

#1381 Tr/qodo installation
  README.md
  docs/docs/installation/pr_agent_pro.md
Labels: Review effort [1-5]: 1

#1386 Tr/self check
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
  tests/health_test/main.py
Labels: Review effort [1-5]: 3

#1388 docs: reorganize and enhance best practices documentation in improve.md
  docs/docs/tools/improve.md
Labels: Review effort [1-5]: 1

#1390 Fix doc for Github Actions
  docs/docs/usage-guide/automations_and_usage.md
Labels: Review effort [1-5]: 1

#1391 feat: add thumbs up/down support and refactor code suggestions handling
  docs/docs/tools/improve.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 4

#1387 Introduce to weak model
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/git_providers/utils.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_help_message.py
  pr_agent/tools/pr_line_questions.py
  pr_agent/tools/pr_questions.py
  pr_agent/tools/pr_reviewer.py
  pr_agent/tools/pr_update_changelog.py
Labels: Review effort [1-5]: 2

#1392 docs: remove model_weak configuration and simplify model selection
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
Labels: Review effort [1-5]: 2

#1394 Update README.md
  README.md
Labels: Review effort [1-5]: 1

#1395 Update review.md
  docs/docs/tools/review.md
Labels: Review effort [1-5]: 1

#1396 Similar Code: Add PR Body License Documentation
  docs/docs/core-abilities/static_code_analysis.md
  docs/docs/tools/similar_code.md
Labels: Review effort [1-5]: 1

#1397 Add support for `gemini/gemini-2.0-flash-exp` model
  pr_agent/algo/__init__.py
Labels: Review effort [1-5]: 1

#1384 Add --version command and version metadata
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/algo/utils.py
  pr_agent/cli.py
  pyproject.toml
Labels: Review effort [1-5]: 2

#1401 docs: simplify default tool configurations and update documentation
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/settings/configuration.toml
Labels: Review effort [1-5]: 1

#1403 feat: enhance code review output with collapsible code snippets
  pr_agent/algo/utils.py
  pr_agent/git_providers/github_provider.py
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_reviewer.py
Labels: Review effort [1-5]: 4

#1407 fix: only publish empty code suggestions when configured
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 1

#1402 Add support for OpenAI `o1` model and snapshot version `o1-2024-12-17`
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: Review effort [1-5]: 1

#1410 Tr/update changelog fix
  docs/docs/tools/update_changelog.md
  pr_agent/algo/__init__.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_update_changelog_prompts.toml
  pr_agent/tools/pr_update_changelog.py
Labels: Review effort [1-5]: 2

#1412 feat: add dedent option to code snippet formatting
  pr_agent/algo/types.py
  pr_agent/algo/utils.py
Labels: Review effort [1-5]: 2

#1413 Document an example on how to configure PR Agent using environment variables
  .gitignore
  docs/docs/installation/locally.md
Labels: Review effort [1-5]: 1

#1416 refactor: remove legacy code suggestions feature from review tool
  README.md
  docs/docs/tools/review.md
  docs/docs/usage-guide/automations_and_usage.md
  pr_agent/agent/pr_agent.py
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_information_from_user.py
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_convert_to_markdown.py
Labels: Review effort [1-5]: 2

#1420 fix: improve line extraction from files with missing content
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/utils.py
Labels: Review effort [1-5]: 2

#1423 Tr/describe v2
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/git_providers/github_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_description.py
Labels: Review effort [1-5]: 4

#1425 fix: restrict sensitive configuration parameters in CLI arguments
  pr_agent/agent/pr_agent.py
Labels: Review effort [1-5]: 2

#1426 fix: sanitize Ask tool answers to prevent markdown formatting issues
  pr_agent/tools/pr_line_questions.py
  pr_agent/tools/pr_questions.py
Labels: Review effort [1-5]: 1

#1421 Update Groq models and tokens
  pr_agent/algo/__init__.py
Labels: Review effort [1-5]: 1

#1428 Update README.md
  README.md
Labels: Review effort [1-5]: 1

#1429 fix: improve PR description and title field descriptions for clarity
  pr_agent/algo/pr_processing.py
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_description.py
  tests/unittest/test_extend_patch.py
Labels: Review effort [1-5]: 1
