Repository qodo-ai/pr-agent, pull requests merged in 2024-01, with the labels that each got.

#558 feat: Add SOC2 compliance review feature to PR agent 💎
  README.md
  docs/REVIEW.md
  pr_agent/settings/configuration.toml
Labels: Review effort [1-5]: 2

#559 feat: Fix typo
  pr_agent/settings/pr_add_docs.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
Labels: Review effort [1-5]: 1

#560 Drop support for python 3.9
  pyproject.toml
Labels: Review effort [1-5]: 1

#563 Refine the prompt for `add_docs` command
  pr_agent/settings/pr_add_docs.toml
Labels: Review effort [1-5]: 1

#565 Remove old 'enable_file_walkthrough' mode
  docs/DESCRIBE.md
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_description.py
Labels: enhancement, Review effort [1-5]: 2

#561 Fix `get_user_description`
  pr_agent/git_providers/git_provider.py
Labels: Review effort [1-5]: 2

#566 Fix failing `/config` command
  pr_agent/tools/pr_config.py
Labels: Review effort [1-5]: 1

#567 Add support for Azure OpenAI in LangChainOpenAIHandler
  pr_agent/algo/ai_handlers/langchain_ai_handler.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/algo/pr_processing.py
Labels: Review effort [1-5]: 3

#568 Enhancement: Improved Extraction and Placement of User Descriptions in PRs
  pr_agent/git_providers/git_provider.py
  pr_agent/tools/pr_description.py
Labels: enhancement, Review effort [1-5]: 2

#569 Add toggle to automatically enable `/improve --extended`
  docs/IMPROVE.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 2

#570 📚 Minor update to REVIEW.md for inclusive language
  docs/REVIEW.md
Labels: Review effort [1-5]: 1

#571 Enhance Documentation and Configuration of 'describe' Tool
  README.md
  Usage.md
  docs/DESCRIBE.md
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_description_prompts.toml
Labels: Review effort [1-5]: 2

#572 describe docs
  docs/DESCRIBE.md
  pr_agent/algo/utils.py
Labels: Review effort [1-5]: 1

#573 feat: Update adaptive collapsible file list logic in pr_description.py
  pr_agent/tools/pr_description.py
Labels: Review effort [1-5]: 2

#574 Enhance and reorganize documentation for review and describe tools
  docs/DESCRIBE.md
  docs/REVIEW.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_reviewer.py
Labels: Review effort [1-5]: 2

#575 docs: Enhance 'improve' tool documentation and update 'DESCRIBE.md' w…
  README.md
  docs/DESCRIBE.md
  docs/IMPROVE.md
Labels: Review effort [1-5]: 1

#578 feat: Update atlassian-python-api version in requirements.txt
  requirements.txt
Labels: Review effort [1-5]: 1

#580 feat: Add debug logs to git_provider and pr_description modules
  pr_agent/git_providers/git_provider.py
  pr_agent/tools/pr_description.py
Labels: Review effort [1-5]: 2

#579 Enhancements to Logging, Help Messages, and PR Descriptions and Reviews
  docs/DESCRIBE.md
  docs/IMPROVE.md
  docs/REVIEW.md
  pr_agent/git_providers/git_provider.py
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Review effort [1-5]: 4

#585 Enhancement: Update GitLab link generation to support self-managed GitLab server and different projects
  pr_agent/git_providers/gitlab_provider.py
Labels: Review effort [1-5]: 1

#586 ask helper
  docs/ASK.md
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_questions_prompts.toml
  pr_agent/tools/pr_questions.py
Labels: Review effort [1-5]: 2

#584 Fix link formatting for relevant_line
  pr_agent/algo/utils.py
Labels: Review effort [1-5]: 1

#587 Enhancement: Improve PR-Agent Tool with Custom Labels, Extra Instructions, and Summarize Mode
  pr_agent/servers/help.py
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Review effort [1-5]: 3

#588 Ignore .DS_Store files
  .gitignore
Labels: Review effort [1-5]: 1

#597 Hl/improve UI table
  pr_agent/algo/utils.py
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
Labels: enhancement, Review effort [1-5]: 3

#590 Fixed Run from source instructions for Python
  INSTALL.md
Labels: Review effort [1-5]: 1

#598 Enhancements to the 'improve' tool and updates to the related documentation
  docs/IMPROVE.md
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#600 readme updates
  README.md
  docs/IMPROVE.md
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 1

#601 Readme Inline file summary 💎
  README.md
  docs/DESCRIBE.md
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#603 Update README.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#605 No suggestions found
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement, Review effort [1-5]: 1

#581 Enhancement of AzureDevopsProvider with new functionalities and refactoring
  pr_agent/git_providers/azuredevops_provider.py
Labels: enhancement, Review effort [1-5]: 4

#607 feat: Improve error handling and code readability in pr_agent tools
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: enhancement, Review effort [1-5]: 2

#594 Enhanced Comment Verification and Fallback Mechanism for Inline Comment Publishing
  pr_agent/git_providers/github_provider.py
  pr_agent/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 4

#614 feat: Add custom suggestions tool to README.md
  README.md
  docs/CUSTOM_SUGGESTIONS.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#615 Update README.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#613 Add changes title of files and improve table style and alignments
  README.md
  docs/DESCRIBE.md
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_description.py
Labels: enhancement, Review effort [1-5]: 3

#616 update default config for inline_file_summary to false
  pr_agent/settings/configuration.toml
Labels: enhancement, Review effort [1-5]: 1

#618 Enhance Documentation for "Inline File Walkthrough" Feature
  docs/DESCRIBE.md
  pr_agent/servers/help.py
Labels: documentation, Review effort [1-5]: 1

#612 Update README.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#620 Configuration updates
  README.md
  docs/IMPROVE.md
  docs/REVIEW.md
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_similar_issue.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#624 small fixes
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#622 docs: fix file name
  README.md
  docs/Full_environments.md
Labels: documentation, Review effort [1-5]: 1

#627 Tr/updates2
  Usage.md
  pr_agent/servers/help.py
Labels: documentation, Review effort [1-5]: 1

#628 tests readme
  README.md
  docs/TEST.md
  pr_agent/settings/configuration.toml
Labels: documentation, enhancement, Review effort [1-5]: 2

#629 s
  README.md
  pr_agent/settings/configuration.toml
Labels: documentation, Review effort [1-5]: 1

#630 Enhancements in Patch Formatting and Code Suggestions Handling
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  pr_agent/settings/pr_add_docs.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: enhancement
