Repository qodo-ai/pr-agent, pull requests merged in 2025-07, with the labels that each got.

#1911 add support for PR sequence diagram in description markers
  docs/docs/tools/describe.md
  pr_agent/servers/help.py
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_description.py
Labels: Review effort 2/5

#1913 clarify that Fetching Ticket Context affects Ask tool
  README.md
  docs/docs/core-abilities/fetching_ticket_context.md
  docs/docs/index.md
Labels: Review effort 1/5

#1922 fix: Remove trailing comma in gerrit provider prepare_repo function
  pr_agent/git_providers/gerrit_provider.py
Labels: Review effort 1/5

#1923 fix: Correct resultsContainer handling
  docs/docs/ai_search/index.md
Labels: Review effort 2/5

#1927 docs: improve installation for various providers
  docs/docs/installation/azure.md
  docs/docs/installation/bitbucket.md
  docs/docs/installation/gitea.md
  docs/docs/installation/gitlab.md
  docs/docs/installation/locally.md
Labels: Review effort 1/5

#1931 fix: clean up PR title formatting before publishing
  pr_agent/tools/pr_description.py
Labels: Review effort 2/5

#1942 docs: A new compliance tool
  README.md
  docs/docs/index.md
  docs/docs/tools/compliance.md
  docs/docs/tools/index.md
  docs/mkdocs.yml
Labels: Review effort 2/5

#1944 Tr/describe redesign
  docs/docs/tools/describe.md
  pr_agent/algo/utils.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_description.py
  tests/unittest/test_convert_to_markdown.py
Labels: Review effort 4/5

#1933 docs: add detailed configuration examples for GitHub Actions models
  docs/docs/installation/github.md
  docs/docs/usage-guide/automations_and_usage.md
Labels: Review effort 2/5

#1945 fix: update documentation for tools
  docs/docs/tools/help_docs.md
  docs/docs/tools/improve_component.md
  docs/docs/tools/review.md
  docs/docs/tools/similar_code.md
  docs/docs/tools/test.md
Labels: Review effort 1/5

#1956 merge the docs of chrome extension into one page
  docs/docs/chrome-extension/index.md
Labels: Review effort 2/5

#1957 update recent updates and add gitlab issues docs
  docs/docs/core-abilities/fetching_ticket_context.md
  docs/docs/recent_updates/index.md
  docs/docs/tools/custom_labels.md
  docs/docs/tools/describe.md
  docs/docs/tools/pr_to_ticket.md
Labels: Review effort 1/5

#1961 Add high-level suggestions to docs
  docs/docs/core-abilities/high_level_suggestions.md
  docs/docs/core-abilities/index.md
  docs/docs/recent_updates/index.md
Labels: Review effort 2/5
