Repository qodo-ai/pr-agent, pull requests merged in 2025-02, with the labels that each got.

#1510 Use `pip install` with `--no-cache-dir` in Dockerfiles
  docker/Dockerfile
  docker/Dockerfile.lambda
Labels: Review effort [1-5]: 1

#1514 feat: improve code suggestions table with impact levels and styling
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 2

#1515 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Review effort [1-5]: 1

#1517 Create SECURITY.md
  SECURITY.md
Labels: Review effort [1-5]: 1

#1522 docs: update README with new design and remove outdated news
  README.md
  docs/docs/overview/pr_agent_pro.md
Labels: Review effort [1-5]: 1

#1532 fix: update review effort label format to use X/5 notation
  pr_agent/tools/pr_reviewer.py
Labels: Review effort [1-5]: 1

#1534 feat: improve help tool with markdown header formatting and error han…
  pr_agent/settings/pr_help_prompts.toml
  pr_agent/tools/pr_help_message.py
Labels: Review effort 2/5

#1531 Add : pull_request_target event on GitHub Actions integration
  pr_agent/servers/github_action_runner.py
Labels: Review effort [1-5]: 1

#1536 Use `pip install` with `--no-cache-dir` in `Dockerfile.github_action`
  Dockerfile.github_action
Labels: Review effort 1/5

#1537 Refactoring `LiteLLMAIHandler` class for better using reasoning models
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: Review effort 2/5

#1545 Update README.md
  README.md
Labels: Review effort 1/5

#1548 Update README.md
  README.md
Labels: Review effort 1/5

#1543 docs: add documentation for new `improve` `more` feature
  docs/docs/tools/improve.md
Labels: Review effort 1/5

#1539 Support generally available `gemini-2.0-flash`
  pr_agent/algo/__init__.py
Labels: Review effort 1/5

#1550 Update README.md
  README.md
Labels: Review effort 1/5

#1551 feat: add support for custom reasoning models
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/configuration.toml
Labels: Review effort 2/5

#1552 docs
  docs/docs/usage-guide/qodo_merge_models.md
Labels: Review effort 1/5

#1559 feat: add current date to PR review metadata
  pr_agent/agent/pr_agent.py
  pr_agent/algo/cli_args.py
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_reviewer.py
Labels: Review effort 1/5

#1529 Added sub-issue fetching to enhance PR analysis
  pr_agent/git_providers/github_provider.py
  pr_agent/tools/ticket_pr_compliance_check.py
  tests/unittest/test_fetching_sub_issues.py
Labels: Review effort [1-5]: 3

#1560 Improve documentation formatting and readability
  README.md
  docs/docs/core-abilities/metadata.md
  docs/docs/tools/analyze.md
  docs/docs/tools/ask.md
  docs/docs/tools/custom_prompt.md
  docs/docs/tools/describe.md
  docs/docs/tools/documentation.md
  docs/docs/tools/implement.md
  docs/docs/tools/improve.md
  docs/docs/tools/improve_component.md
  docs/docs/tools/similar_issues.md
  docs/docs/tools/test.md
  docs/docs/usage-guide/automations_and_usage.md
  docs/docs/usage-guide/changing_a_model.md
  docs/mkdocs.yml
Labels: Review effort 1/5

#1565 docs: add auto-approval configuration documentation
  docs/docs/tools/improve.md
  docs/docs/tools/review.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_reviewer.py
Labels: Review effort 1/5

#1566 Tr/ai search
  docs/docs/ai_search/index.md
  docs/mkdocs.yml
  docs/overrides/partials/footer.html
Labels: Review effort 3/5

#1568 feat: improve patch extension with new file content comparison
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  pr_agent/config_loader.py
  tests/unittest/test_extend_patch.py
Labels: Review effort 3/5

#1556 Fix prompt to not output diff prefixes in existing_code,improved_code pydantic definitions
  pr_agent/algo/utils.py
Labels: Review effort 1/5

#1555 Enhanced gitlab webhook handling for push events without object_attributes
  pr_agent/servers/gitlab_webhook.py
Labels: Review effort 2/5

#1571 Docs: fix static code and remove Incremental PR review
  README.md
  docs/docs/index.md
Labels: Review effort 1/5

#1570 feat: support Claude 3.7 Sonnet
  pr_agent/algo/__init__.py
  requirements.txt
Labels: Review effort 1/5

#1572 docs: add auto-approve feature to platform support matrix
  README.md
  docs/docs/index.md
  docs/docs/tools/improve.md
Labels: Review effort 1/5

#1561 Support reasoning effort via configuration
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
Labels: Review effort 2/5

#1564 Fix/support litellm extra headers
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: Review effort 2/5

#1583 feat: enhance Azure DevOps integration with improved error handling a…
  pr_agent/algo/utils.py
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/servers/azuredevops_server_webhook.py
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_description.py
Labels: Review effort 2/5

#1584 Tr/gitlab fix
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_description.py
Labels: Review effort 2/5

#1575 gitlab webhook automatically trigger pr_command when MR changes from Draft to Ready
  pr_agent/servers/gitlab_webhook.py
Labels: Review effort 3/5

#1579 Add a language configuration to translate language generated by QodoM…
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/agent/pr_agent.py
  pr_agent/settings/configuration.toml
Labels: Review effort 2/5
