Repository qodo-ai/pr-agent, pull requests merged in 2025-04, with the labels that each got.

#1670 Add support for documentation content exceeding token limits
  pr_agent/algo/token_handler.py
  pr_agent/config_loader.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/bitbucket_server_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_help_docs_headings_prompts.toml
  pr_agent/tools/pr_help_docs.py
Labels: Review effort 3/5

#1671 fix: add error handling for missing review data in PR reviewer
  pr_agent/tools/pr_reviewer.py
Labels: Review effort 1/5

#1667 Update logging configuration to use dynamic log level from settings
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/servers/azuredevops_server_webhook.py
  pr_agent/servers/bitbucket_app.py
  pr_agent/servers/bitbucket_server_webhook.py
  pr_agent/servers/github_app.py
  pr_agent/servers/github_polling.py
  pr_agent/servers/gitlab_webhook.py
  pr_agent/settings/configuration.toml
Labels: Review effort 1/5

#1674 Docs: Add Core Abilities / Interactivity
  docs/docs/core-abilities/index.md
  docs/docs/core-abilities/interactivity.md
  docs/mkdocs.yml
Labels: Review effort 1/5

#1677 Updated Dockerfile.lambda for python version 3.12
  docker/Dockerfile.lambda
Labels: Review effort 1/5

#1679 Add support of OpenAI GPT-4.5 Preview model
  pr_agent/algo/__init__.py
Labels: Review effort 1/5

#1682 docs: Add RAG applications and alphabetize documentation
  docs/docs/core-abilities/index.md
  docs/docs/core-abilities/interactivity.md
  docs/docs/core-abilities/rag_context_enrichment.md
  docs/mkdocs.yml
Labels: Review effort 1/5

#1689 docs: add Chrome extension options documentation page
  docs/docs/chrome-extension/options.md
  docs/mkdocs.yml
Labels: Review effort 1/5

#1680 Add support of Meta's Llama 4 Scout and Maverick 17b from Groq Cloud
  pr_agent/algo/__init__.py
Labels: Review effort 1/5

#1684 Add support of xAI and their Grok-2 & Grok-3 model
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/.secrets_template.toml
Labels: Review effort 2/5

#1685 Add support of Gemini 2.5 Pro preview model
  pr_agent/algo/__init__.py
Labels: Review effort 1/5

#1694 Add support of OpenAI GPT-4.1 model family
  pr_agent/algo/__init__.py
Labels: Review effort 1/5

#1691 Fix Discord link in README
  README.md
Labels: Review effort 1/5

#1692 Correct the tools guide link in the locally installation doc
  docs/docs/installation/locally.md
Labels: Review effort 1/5

#1693 Improve Markdown format in model configuration guide
  docs/docs/usage-guide/changing_a_model.md
Labels: Review effort 1/5

#1698 Azure AD authentication for OpenAI services
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/.secrets_template.toml
Labels: Review effort 2/5

#1701 Add new tool for scanning repository discussions and generating best …
  README.md
  docs/docs/index.md
  docs/docs/tools/index.md
  docs/docs/tools/scan_repo_discussions.md
  docs/mkdocs.yml
Labels: Review effort 1/5

#1702 Add OpenAI o3 & 4o-mini reasoning models
  pr_agent/algo/__init__.py
Labels: Review effort 1/5

#1707 Add support for Mistral and Codestral models
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: Review effort 2/5

#1708 Upgrade litellm to v1.66.3
  requirements.txt
Labels: Review effort 1/5

#1703 docs: updated bitbucket pipeline docs
  docs/docs/installation/bitbucket.md
Labels: Review effort 1/5

#1711 Feature/simplified bitbucket pipeline
  docs/docs/installation/bitbucket.md
Labels: Review effort 1/5

#1710 Replace default o3-mini with o4-mini
  docs/docs/chrome-extension/index.md
  docs/docs/installation/locally.md
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/settings/configuration.toml
Labels: Review effort 1/5

#1712 Update model references from o3-mini to o4-mini and add Gemini models
  docs/docs/overview/pr_agent_pro.md
  docs/docs/usage-guide/qodo_merge_models.md
  pr_agent/algo/__init__.py
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
Labels: Review effort 2/5

#1715 Improve field descriptions for code suggestion model clarity and brevity
  pr_agent/settings/code_suggestions/pr_code_suggestions_prompts_not_decoupled.toml
Labels: Review effort 1/5

#1687 Improvement: Enhance ask_line tool by adding PR review comment threads as context
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_line_questions_prompts.toml
  pr_agent/tools/pr_line_questions.py
Labels: Review effort 3/5

#1719 Add documentation for chat functionality in code suggestions
  docs/docs/tools/improve.md
Labels: Review effort 1/5

#1726 Tr/multi model prompt
  docs/docs/tools/improve.md
  docs/docs/usage-guide/qodo_merge_models.md
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/settings/code_suggestions/pr_code_suggestions_prompts_not_decoupled.toml
  pr_agent/settings/code_suggestions/pr_code_suggestions_reflect_prompts.toml
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort 2/5

#1721 Docs: fix typo in response_language setting inside .pr-agent.toml configuration guide
  docs/docs/usage-guide/additional_configurations.md
Labels: Review effort 1/5

#1718 Update .gitignore and fix license format in pyproject.toml
  .gitignore
  pyproject.toml
Labels: Review effort 1/5

#1728 Fix type hint for get_pr_description method and clean up whitespace
  pr_agent/git_providers/git_provider.py
Labels: Review effort 1/5

#1731 docs: update Gemini model path from google_ai_studio to gemini in con…
  docs/docs/usage-guide/changing_a_model.md
Labels: Review effort 1/5

#1735 docs: add data privacy and contributing sections to README and update news
  README.md
Labels: Review effort 1/5
