Repository qodo-ai/pr-agent, pull requests merged in 2025-03, with the labels that each got.

#1594 chore: add bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
  pr_agent/algo/__init__.py
Labels: Review effort 1/5

#1602 chore: update version, dependencies and company branding
  pyproject.toml
  requirements.txt
Labels: Review effort 1/5

#1604 docs: fix usage-guide/automations_and_usage.md in mistake link
  docs/docs/usage-guide/automations_and_usage.md
Labels: Review effort 1/5

#1607 docs: update model references to Claude 3.7 Sonnet and o3-mini throug…
  README.md
  docs/docs/chrome-extension/index.md
  docs/docs/faq/index.md
  docs/docs/finetuning_benchmark/index.md
  docs/docs/installation/locally.md
  docs/docs/overview/pr_agent_pro.md
  docs/docs/tools/improve.md
  docs/docs/usage-guide/additional_configurations.md
  docs/docs/usage-guide/qodo_merge_models.md
Labels: Review effort 1/5

#1610 fix: validate one-liner suggestions to prevent repeating existing code
  pr_agent/agent/pr_agent.py
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort 2/5

#1611 feat: add DeepInfra support
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/.secrets_template.toml
Labels: Review effort 2/5

#1612 fix: repeat processing files to ignore
  pr_agent/algo/pr_processing.py
Labels: Review effort 1/5

#1605 Support extended thinking for model `claude-3-7-sonnet-20250219`
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/configuration.toml
Labels: Review effort 2/5

#1613 docs: update auto-approval documentation with clearer configuration
  docs/docs/tools/improve.md
  pr_agent/algo/cli_args.py
Labels: Review effort 1/5

#1614 Fix default value for extended_thinking_max_output_tokens
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/configuration.toml
Labels: Review effort 1/5

#1615 Update improve.md
  docs/docs/tools/improve.md
Labels: Review effort 1/5

#1616 Tr/updates34
  pr_agent/algo/git_patch_processing.py
  pr_agent/algo/language_handler.py
  pr_agent/algo/pr_processing.py
  pr_agent/algo/utils.py
  pr_agent/config_loader.py
  pr_agent/settings/code_suggestions/pr_code_suggestions_prompts.toml
  pr_agent/settings/code_suggestions/pr_code_suggestions_prompts_not_decoupled.toml
  pr_agent/settings/code_suggestions/pr_code_suggestions_reflect_prompts.toml
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_sort_code_suggestions_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_line_questions.py
  tests/unittest/test_extend_patch.py
Labels: Review effort 3/5

#1624 Move Config Content Inside Collapsible Titles
  docs/docs/tools/describe.md
  docs/docs/tools/review.md
Labels: Review effort 1/5

#1626 chore: update pr_reviewer_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: Review effort 1/5

#1625 Hl/update configs docs
  docs/docs/usage-guide/configuration_options.md
Labels: Review effort 1/5

#1628 docs: Update description of gitlab-webhook installation.
  docs/docs/installation/gitlab.md
Labels: Review effort 1/5

#1636 Update azuredevops_provider.py
  pr_agent/git_providers/azuredevops_provider.py
Labels: Review effort 1/5

#1637 doc: Add info about ollama context length
  docs/docs/usage-guide/changing_a_model.md
Labels: Review effort 1/5

#1644 Adding a new tool: /help_docs
  docs/docs/tools/help_docs.md
  docs/mkdocs.yml
  pr_agent/agent/pr_agent.py
  pr_agent/algo/token_handler.py
  pr_agent/cli.py
  pr_agent/config_loader.py
  pr_agent/git_providers/bitbucket_provider.py
  pr_agent/git_providers/bitbucket_server_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/servers/help.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_help_docs_prompts.toml
  pr_agent/tools/pr_help_docs.py
  pr_agent/tools/pr_help_message.py
  requirements.txt
Labels: Review effort 4/5

#1647 Bugfix: Incorrect git url in case of GitHub app
  pr_agent/git_providers/github_provider.py
Labels: Review effort 2/5

#1648 Update Docs: Company Codebase Overview, RAG Integration & Configuration
  docs/docs/core-abilities/code_oriented_yaml.md
  docs/docs/core-abilities/company_codebase.md
  docs/docs/core-abilities/index.md
  docs/docs/usage-guide/qodo_merge_models.md
  docs/mkdocs.yml
Labels: Review effort 1/5

#1634 fix: Logging and Commenting
  pr_agent/servers/github_app.py
Labels: Review effort 2/5

#1650 Add codebase references screenshot to company_codebase documentation
  docs/docs/core-abilities/company_codebase.md
Labels: Review effort 1/5

#1649 docs: update configuration options and improve wiki documentation cla…
  docs/docs/tools/improve.md
  docs/docs/usage-guide/configuration_options.md
  docs/docs/usage-guide/enabling_a_wiki.md
Labels: Review effort 2/5

#1651 Add support for publishing comments on issues in GitHub provider
  pr_agent/git_providers/github_provider.py
  pr_agent/tools/pr_help_docs.py
Labels: Review effort 2/5

#1653 Update main readme file + improve help docs
  README.md
  docs/docs/tools/help_docs.md
Labels: Review effort 1/5

#1658 Fix for bug in get_canonical_url_parts when a new issue created, without git url provided
  pr_agent/git_providers/github_provider.py
Labels: Review effort 2/5

#1659 Update bitbucket related documentation
  docs/docs/usage-guide/automations_and_usage.md
  docs/docs/usage-guide/configuration_options.md
Labels: Review effort 1/5

#1663 Improve code analysis instructions for handling partial code blocks i…
  pr_agent/settings/code_suggestions/pr_code_suggestions_prompts_not_decoupled.toml
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: Review effort 1/5

#1662 Tr/more protections gitlab
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/tools/pr_questions.py
Labels: Review effort 2/5
