Repository qodo-ai/pr-agent, pull requests merged in 2025-06, with the labels that each got.

#1838 docs: add Linear integration to ticket context fetching documentation
  docs/docs/core-abilities/fetching_ticket_context.md
Labels: Review effort 1/5

#1840 Reorganize and Enhance Tools Documentation with Improved Navigation and Consistency
  README.md
  docs/docs/tools/index.md
  docs/mkdocs.yml
Labels: Review effort 2/5

#1853 Add Google Gemini 2.5 Pro Preview 06-05
  pr_agent/algo/__init__.py
Labels: Review effort 1/5

#1851 chore: add APAC region endpoints for Bedrock Anthropic Claude models
  pr_agent/algo/__init__.py
Labels: Review effort 1/5

#1872 tickets docs
  docs/docs/core-abilities/fetching_ticket_context.md
Labels: Review effort 2/5

#1873 docs: refactor auto-approval documentation into dedicated core abilit…
  docs/docs/core-abilities/auto_approval.md
  docs/docs/core-abilities/index.md
  docs/docs/tools/improve.md
  docs/mkdocs.yml
Labels: Review effort 2/5

#1868 feat: support self-signed gitea cert
  docs/docs/installation/gitea.md
  pr_agent/git_providers/gitea_provider.py
Labels: Review effort 2/5

#1880 fix: typos, grammar
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/algo/utils.py
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_help_prompts.toml
  pr_agent/settings/pr_information_from_user_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_help_docs.py
Labels: Review effort 1/5

#1874 feat: Support GitLab webhooks in Lambda functions
  docker/Dockerfile.lambda
  docs/docs/installation/github.md
  docs/docs/installation/gitlab.md
  pr_agent/servers/github_lambda_webhook.py
  pr_agent/servers/gitlab_lambda_webhook.py
Labels: Review effort 3/5

#1895 gemini 2.5 flash/pro GA models
  pr_agent/algo/__init__.py
Labels: Review effort 1/5

#1891 test: auto-trigger /add_docs on PR opened events
  tests/unittest/test_add_docs_trigger.py
Labels: Review effort 3/5

#1892 Add bedrock Llama 4 Scout/Maverick
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/__init__.py
Labels: Review effort 2/5

#1898 feat: support ignoring auto-generated files by language/framework
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/algo/file_filter.py
  pr_agent/config_loader.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/generated_code_ignore.toml
  tests/unittest/test_file_filter.py
Labels: Review effort 3/5

#1904 Tr/suggestions depth
  docs/docs/tools/describe.md
  docs/docs/usage-guide/additional_configurations.md
Labels: Review effort 1/5

#1905 Update docs that Gitlab also supports Incremental Update
  docs/docs/core-abilities/incremental_update.md
Labels: Review effort 1/5
