Repository qodo-ai/pr-agent, pull requests merged in 2025-05, with the labels that each got.

#1738 Use slim Docker image and install git and curl dependencies
  docker/Dockerfile
Labels: Review effort 1/5

#1737 doc: title refinement
  docs/docs/tools/improve.md
Labels: Review effort 1/5

#1742 Azure devops: parse PR url starting from the end
  pr_agent/git_providers/azuredevops_provider.py
  tests/unittest/test_azure_devops_parsing.py
Labels: Review effort 2/5

#1744 Openrouter support
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/.secrets_template.toml
Labels: Review effort 2/5

#1745 fix: Prevent duplicate language instructions in extra_instructions
  pr_agent/agent/pr_agent.py
Labels: Review effort 2/5

#1749 fix(gitlab): trigger when MR changes from draft to ready
  pr_agent/servers/gitlab_webhook.py
Labels: Review effort 2/5

#1753 fix:correct typo in logger parameter from 'artifacts' to 'artifact'
  pr_agent/tools/pr_description.py
Labels: Review effort 1/5

#1759 docs: add information about feedback on draft PRs
  docs/docs/usage-guide/automations_and_usage.md
Labels: Review effort 1/5

#1757 docs: improve readability of improve tool documentation with tabs
  docs/docs/tools/improve.md
Labels: Review effort 1/5

#1760 docs: clarify that .pr_agent.toml can be updated post PR creation
  docs/docs/usage-guide/configuration_options.md
Labels: Review effort 1/5

#1758 fix: avoid duplicate header for list types to prevent markdown break
  pr_agent/tools/pr_description.py
Labels: Review effort 1/5

#1761 docs: add recent updates and future roadmap section to documentation
  docs/docs/recent_updates/index.md
  docs/mkdocs.yml
Labels: Review effort 1/5

#1762 fix: update Docker base image to slim version and install required de…
  Dockerfile.github_action
Labels: Review effort 1/5

#1746 Implement Azure Devops persistent comment
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/git_provider.py
  pr_agent/servers/azuredevops_server_webhook.py
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort 2/5

#1764 Changelog prompt: fix markdown link
  pr_agent/settings/pr_update_changelog_prompts.toml
Labels: Review effort 1/5

#1771 Tr/new benchmark
  docs/docs/core-abilities/index.md
  docs/docs/finetuning_benchmark/index.md
  docs/docs/pr_benchmark/index.md
  docs/docs/usage-guide/index.md
  docs/mkdocs.yml
Labels: Review effort 2/5

#1767 docs: enhance improve.md with manual suggestions for Bitbucket and Gi…
  docs/docs/tools/improve.md
Labels: Review effort 1/5

#1770 fix: add timeout to asyncio.wait during CLI execution to avoid hanging when callback is enabled
  pr_agent/cli.py
Labels: Review effort 2/5

#1785 Add Gemini-2.5-pro-preview-05-06 model and update litellm dependency
  pr_agent/algo/__init__.py
  requirements.txt
Labels: Review effort 1/5

#1778 Cleanup: Remove Unused import and Fix Parameter Typo
  pr_agent/git_providers/utils.py
  pr_agent/identity_providers/identity_provider.py
Labels: Review effort 1/5

#1779 Enable usage of OpenAI like APIs
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: Review effort 1/5

#1786 Pr 1736
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/servers/bitbucket_app.py
  pr_agent/servers/github_app.py
  pr_agent/servers/gitlab_webhook.py
  pr_agent/settings/configuration.toml
  tests/unittest/test_ignore_repositories.py
Labels: Review effort 2/5

#1736 Add ignore_repositories config for PR filtering
  pr_agent/servers/bitbucket_app.py
  pr_agent/servers/github_app.py
  pr_agent/servers/gitlab_webhook.py
  pr_agent/settings/configuration.toml
  tests/unittest/test_ignore_repositories.py
Labels: Review effort 2/5

#1790 Tr/v029
  README.md
  docs/docs/recent_updates/index.md
  tests/unittest/test_try_fix_yaml.py
Labels: Review effort 1/5

#1797 Adding num_max_findings configuration parameter
  docs/docs/tools/review.md
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_reviewer.py
Labels: Review effort 1/5

#1799 Revise the review effort label text in the review document
  docs/docs/tools/review.md
Labels: Review effort 1/5

#1796 Add incremental update to documentation
  docs/docs/core-abilities/incremental_update.md
  docs/docs/core-abilities/index.md
  docs/docs/index.md
  docs/mkdocs.yml
Labels: Review effort 1/5

#1787 #1657 add gitea/forgejo support
  pr_agent/git_providers/__init__.py
  pr_agent/git_providers/gitea_provider.py
  tests/e2e_tests/test_gitea_app.py
  tests/unittest/test_gitea_provider.py
Labels: Review effort 3/5

#1798 Correct typos in documentation and log messages
  docs/docs/installation/github.md
  docs/docs/usage-guide/additional_configurations.md
  docs/docs/usage-guide/configuration_options.md
  pr_agent/git_providers/azuredevops_provider.py
  pr_agent/git_providers/github_provider.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: Review effort 1/5

#1803 fix: reorder exception handling in `LiteLLMAIHandler.chat_completion()`
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: Review effort 1/5

#1809 Update LICENSE
  LICENSE
Labels: Review effort 2/5

#1801 docs: include [aws] in .secrets.template
  pr_agent/settings/.secrets_template.toml
Labels: Review effort 1/5

#1817 Add Grok-3 non-beta model IDs
  pr_agent/algo/__init__.py
Labels: Review effort 1/5

#1816 Add Unit Tests and Improve Documentation for utils.py clip_tokens Function
  pr_agent/algo/utils.py
  tests/unittest/test_clip_tokens.py
Labels: Review effort 2/5

#1823 ensure_ticket_compliance
  docs/docs/tools/improve.md
  pr_agent/settings/configuration.toml
Labels: Review effort 1/5

#1805 Refactor count_tokens method structure in token_handler.py for better extensibility
  pr_agent/algo/token_handler.py
Labels: Review effort 2/5

#1824 Improve/describe tool documentation and make add_diagram feature opt-in by default
  docs/docs/tools/describe.md
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/tools/pr_description.py
Labels: Review effort 2/5

#1829 test: add tests for converting to markdown
  tests/unittest/test_convert_to_markdown.py
Labels: Review effort 2/5

#1831 docs: correct parameter name typo and update description
  docs/docs/tools/describe.md
Labels: Review effort 1/5

#1835 docs: add dedicated "Chat on code suggestions" core ability
  docs/docs/core-abilities/chat_on_code_suggestions.md
  docs/docs/core-abilities/index.md
  docs/docs/tools/implement.md
  docs/docs/tools/improve.md
  docs/mkdocs.yml
Labels: Review effort 2/5

#1837 docs: enhance review.md with ticket compliance labels and merge block…
  docs/docs/tools/review.md
Labels: Review effort 1/5
