Repository qodo-ai/pr-agent, pull requests merged in 2025-08, with the labels that each got.

#1954 feat: Add support for Bedrock custom inference profiles via model_id
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/.secrets_template.toml
  pr_agent/settings/configuration.toml
Labels: Review effort 2/5

#1949 feat: add eyes reaction to GitLab provider
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/servers/gitlab_webhook.py
Labels: Review effort 3/5

#1971 docs: add compliance tool to RAG context enrichment documentation
  docs/docs/core-abilities/rag_context_enrichment.md
  docs/docs/tools/compliance.md
Labels: Review effort 1/5

#1970 Fix: defer file sorting until after token calculation
  pr_agent/algo/pr_processing.py
Labels: Review effort 2/5

#1981 Update GitHub marketplace link
  docs/docs/installation/qodo_merge.md
Labels: Review effort 1/5

#1983 Tr/benchmark
  README.md
  docs/docs/chrome-extension/index.md
  docs/docs/faq/index.md
  docs/docs/overview/pr_agent_pro.md
  docs/docs/pr_benchmark/index.md
  docs/docs/usage-guide/changing_a_model.md
  docs/docs/usage-guide/qodo_merge_models.md
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  requirements.txt
Labels: Review effort 2/5

#1986 fix: update model prefix in litellm_ai_handler and adjust dependencie…
  README.md
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  requirements.txt
Labels: Review effort 2/5

#1988 docs: fix typo in OpenAI model parameter name to search
  docs/docs/usage-guide/changing_a_model.md
Labels: Review effort 1/5

#1972 Update fetching_ticket_context.md
  docs/docs/core-abilities/fetching_ticket_context.md
Labels: Review effort 2/5

#1996 fix: add temperature arg to self reflect of improve
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort 1/5

#1980 feat: enhance BitbucketServerProvider authentication with username and password fallback
  pr_agent/git_providers/bitbucket_server_provider.py
Labels: Review effort 2/5

#2000 Correct variable for url for bitbucket server
  pr_agent/settings/.secrets_template.toml
Labels: Review effort 1/5

#2006 PR reviewer tool: add an opt-in work time estimation
  docs/docs/tools/review.md
  pr_agent/algo/utils.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_reviewer.py
  tests/unittest/test_convert_to_markdown.py
Labels: Review effort 2/5

#2008 Tr/updates23
  pr_agent/algo/utils.py
  pr_agent/settings/code_suggestions/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_description_prompts.toml
  tests/unittest/test_try_fix_yaml.py
Labels: Review effort 2/5

#2011 Set a status for comments on azure devops
  pr_agent/git_providers/azuredevops_provider.py
Labels: Review effort 2/5
