Repository qodo-ai/pr-agent, pull requests merged in 2025-01, with the labels that each got.

#1406 Support pull requests in personal spaces in Bitbucket Server
  pr_agent/git_providers/bitbucket_server_provider.py
  tests/unittest/test_bitbucket_provider.py
Labels: Review effort [1-5]: 2

#1430 docs: update FAQ with new questions and improve formatting
  docs/docs/faq/index.md
Labels: Review effort [1-5]: 1

#1431 fix: improve CLI argument validation for sensitive parameters
  pr_agent/agent/pr_agent.py
Labels: Review effort [1-5]: 2

#1432 fix: reorganize PR description prompt fields and improve clarity
  pr_agent/settings/pr_description_prompts.toml
Labels: Review effort [1-5]: 2

#1417 Add documentation for `/implement` tool and enhance `/test` tool references
  .gitignore
  README.md
  docs/docs/index.md
  docs/docs/overview/index.md
  docs/docs/overview/pr_agent_pro.md
  docs/docs/tools/implement.md
  docs/docs/tools/index.md
  docs/docs/tools/test.md
  docs/mkdocs.yml
Labels: Review effort [1-5]: 2

#1433 Refine `implement` tool documentation and remove outdated notes
  docs/docs/tools/implement.md
Labels: Review effort [1-5]: 1

#1434 Tr/ollama
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/config_loader.py
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_code_suggestions_reflect_prompts.toml
  pr_agent/settings/pr_description_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
  pr_agent/tools/pr_description.py
  pr_agent/tools/pr_reviewer.py
Labels: Review effort [1-5]: 2

#1439 fix: handle newline issues in patch generation
  pr_agent/algo/utils.py
  tests/unittest/test_bitbucket_provider.py
  tests/unittest/test_extend_patch.py
Labels: Review effort [1-5]: 2

#1440 docs: add GitLab support for /implement tool.
  README.md
  docs/docs/index.md
  docs/docs/overview/index.md
Labels: Review effort [1-5]: 1

#1442 fix : pr type rendering with markers
  pr_agent/tools/pr_description.py
Labels: Review effort [1-5]: 1

#1441 fix : support ai title with markers
  pr_agent/tools/pr_description.py
Labels: Review effort [1-5]: 2

#1446 fix: refine code suggestions prompts and avoid package-related comments
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/tools/pr_code_suggestions.py
Labels: Review effort [1-5]: 2

#1448 docs: add missing word
  pr_agent/tools/pr_help_message.py
Labels: Review effort [1-5]: 1

#1452 fix(azure-provider): handle renamed files as new files
  pr_agent/git_providers/azuredevops_provider.py
Labels: Review effort [1-5]: 2

#1454 documentation
  docs/docs/core-abilities/fetching_ticket_context.md
Labels: Review effort [1-5]: 1

#1457 Support deepseek-chat model
  docs/docs/usage-guide/changing_a_model.md
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
  pr_agent/settings/.secrets_template.toml
Labels: Review effort [1-5]: 2

#1455 fix(local_git): add interface func stubs for git local provider
  pr_agent/git_providers/local_git_provider.py
Labels: Review effort [1-5]: 1

#1465 docs: improve diff format documentation and code review instructions
  docs/docs/core-abilities/metadata.md
  docs/docs/tools/improve.md
  docs/docs/usage-guide/enabling_a_wiki.md
  docs/docs/usage-guide/index.md
  docs/mkdocs.yml
  pr_agent/settings/pr_code_suggestions_prompts.toml
  pr_agent/settings/pr_code_suggestions_reflect_prompts.toml
  pr_agent/settings/pr_reviewer_prompts.toml
Labels: Review effort [1-5]: 1

#1467 docs: add target blank to external links in documentation
  docs/docs/chrome-extension/index.md
  docs/docs/installation/index.md
  docs/docs/overview/pr_agent_pro.md
  docs/docs/usage-guide/additional_configurations.md
  docs/docs/usage-guide/introduction.md
Labels: Review effort [1-5]: 1

#1466 Add `vertex_ai/gemini-2.0-flash-exp`
  pr_agent/algo/__init__.py
Labels: Review effort [1-5]: 1

#1474 QM
  docs/docs/chrome-extension/data_privacy.md
  docs/docs/chrome-extension/features.md
  docs/docs/chrome-extension/index.md
  docs/docs/faq/index.md
  docs/docs/index.md
  docs/docs/installation/azure.md
  docs/docs/installation/bitbucket.md
  docs/docs/installation/index.md
  docs/docs/installation/locally.md
  docs/docs/installation/pr_agent_pro.md
  docs/docs/overview/data_privacy.md
  docs/docs/overview/index.md
  docs/docs/overview/pr_agent_pro.md
  docs/docs/tools/custom_labels.md
  docs/docs/tools/help.md
  docs/docs/tools/improve.md
  docs/docs/tools/index.md
  docs/docs/usage-guide/PR_agent_pro_models.md
  docs/docs/usage-guide/automations_and_usage.md
  docs/docs/usage-guide/configuration_options.md
  docs/docs/usage-guide/index.md
  docs/mkdocs.yml
Labels: Review effort [1-5]: 2

#1469 Remove false log that file was modified, but no patch found for bitbucket server
  pr_agent/git_providers/bitbucket_server_provider.py
Labels: Review effort [1-5]: 1

#1473 Add support model deepseek/deepseek-reasoner
  pr_agent/algo/__init__.py
  pr_agent/algo/ai_handlers/litellm_ai_handler.py
Labels: Review effort [1-5]: 1

#1475 docs: reorganize installation documentation structure
  docs/docs/installation/azure.md
  docs/docs/installation/bitbucket.md
  docs/docs/installation/index.md
  docs/docs/installation/locally.md
  docs/docs/installation/pr_agent.md
  docs/docs/installation/qodo_merge.md
  docs/mkdocs.yml
Labels: Review effort [1-5]: 2

#1477 refactor: simplify review effort label format and remove maximal effo…
  docs/docs/tools/review.md
  pr_agent/settings/configuration.toml
  pr_agent/tools/pr_reviewer.py
Labels: Review effort: 2/5

#1484 Add `IMPLEMENT` tool and reorganize help message content
  pr_agent/tools/pr_help_message.py
Labels: Review effort [1-5]: 1

#1486 feat: enhance ticket compliance analysis with human verification tracking
  pr_agent/algo/utils.py
  pr_agent/settings/pr_reviewer_prompts.toml
  pr_agent/tools/ticket_pr_compliance_check.py
Labels: Review effort [1-5]: 3

#1485 Tr/docs best practice
  docs/docs/core-abilities/auto_best_practices.md
  docs/docs/core-abilities/index.md
  docs/docs/tools/improve.md
  docs/mkdocs.yml
  pr_agent/settings/configuration.toml
  pr_agent/settings/pr_code_suggestions_prompts.toml
Labels: Review effort [1-5]: 2

#1490 Update config.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/miscellaneous.yml
Labels: Review effort [1-5]: 1

#1495 fix: remove shell rendering from issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/miscellaneous.yml
Labels: Review effort [1-5]: 1

#1498 fix: update issue template fields and Discord link
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/miscellaneous.yml
Labels: Review effort [1-5]: 1

#1500 Add CONTRIBUTING.md with contribution guidelines and setup instructions
  CONTRIBUTING.md
Labels: Review effort [1-5]: 1

#1506 fix: add fallback for parsing AI responses with leading '+' symbols
  pr_agent/algo/utils.py
Labels: Review effort [1-5]: 2
