Repository qodo-ai/pr-agent, pull requests merged in 2025-09, with the labels that each got.

#2018 fix: correct variable name for last merge source commit in Azure DevOps provider
  pr_agent/git_providers/azuredevops_provider.py
Labels: Review effort 1/5

#2021 feat: enhance documentation with additional repository metadata secti…
  docs/docs/usage-guide/additional_configurations.md
  docs/docs/usage-guide/changing_a_model.md
  docs/docs/usage-guide/index.md
  docs/docs/usage-guide/qodo_merge_models.md
  docs/mkdocs.yml
  pr_agent/settings/configuration.toml
Labels: Review effort 2/5

#2014 [GitLab] Submodule expansion functionality added
  docs/docs/recent_updates/index.md
  docs/docs/usage-guide/additional_configurations.md
  pr_agent/git_providers/gitlab_provider.py
  pr_agent/settings/configuration.toml
  tests/unittest/test_gitlab_provider.py
Labels: Possible security concern, Review effort 3/5

#2035 Fix typo on docs
  docs/docs/core-abilities/high_level_suggestions.md
Labels: Review effort 1/5

#2034 Update Qodo Merge installation for Gitlab documentation
  docs/docs/installation/qodo_merge.md
Labels: Possible security concern, Review effort 2/5
